### ISSUE TITLE
[Access] Fix TODO's for unstaked node

### ISSUE THREAD

**Issue by smnzhu** [onflow/flow-go#1126]
TODO's from DHT PR:

- [x] https://github.com/onflow/flow-go/pull/1098#discussion_r687033083

- [x] https://github.com/onflow/flow-go/pull/1098/files#r687050836 ( updating from zeroID to use idTranslator)

**Comment by huitseeker** [comment]
So #1115 has a pending fix in #1163 , and the ZeroID update is probably blocked on #1133 IIUC.

**Comment by huitseeker** [comment]
This should be done @vishalchangrani @simonhf (as part of #1133 et al.)
