### ISSUE TITLE
Unable to build flow node from source

### ISSUE THREAD

**Issue by dsbrgg** [onflow/flow-go#1369]
I've been trying to build through docker an instance of an `access`  flow node. Here's the part of my current Dockerfile which I request for the zipped binary and try to build the node (using `golang:1.15` image), `FLOW_VERSION` used were `0.20.5` (first error) and `0.22.2` (second error):

```
ADD https://github.com/onflow/flow-go/archive/refs/tags/v${FLOW_VERSION}.tar.gz /tmp/flow-go.tar.gz

RUN tar xzf /tmp/flow-go.tar.gz -C /tmp \
  && rm -rf /tmp/flow-go.tar.gz \
  && cd /tmp/flow-go-${FLOW_VERSION} \
  && GO11MODULE=on CGO_ENABLED=1 GOOS=linux GOARCH=amd64 \
  go build -o ./app ./cmd/${FLOW_NODE_TYPE}
```

 The problems that I've been having seems to stem from not having proper access to some of the internal repos, I'll leave some logs that might give an idea of my problem:

```
#8 28.51 go: github.com/onflow/cadence@v0.18.1-0.20210715170431-cd7a7a483000: reading github.com/dapperlabs/cadence-internal/go.mod at revision v0.18.0-patch.6: unknown revision v0.18.0-patch.6
```

and

```
8 37.06 go: github.com/onflow/atree@v0.0.0-20210922123047-5e9b56cf01dd: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/db392155395003ec64ede82caba0be55603c47c0862c4e5dd9a86e3f28d64f5d: exit status 128:
#8 37.06        fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

The steps that I'm using to build the node from source are the same as [this Dockerfile RUN](https://github.com/onflow/flow-go/blob/master/cmd/Dockerfile#L42) but without the `--mount` flags and `ldflags` set for the `go build` command. 

Is it possible to have access to these repos to properly build the node from source? Or maybe I'm missing something that is important to build it.

**Comment by fxamacker** [comment]
github.com/onflow/atree was in a private repo and it was open sourced today.
