### ISSUE TITLE
[State sync engine] Implement block stores

### ISSUE THREAD

**Issue by smnzhu** [onflow/flow-go#1450]
We will need to implement the [Blockstore](https://pkg.go.dev/github.com/ipfs/go-ipfs-blockstore) interface for various entities in order to use them with bitswap:
- Collections
- Events
- TrieUpdates
- TransactionResult?
- Need a separate Blockstore for MerkleDAG nodes which are used for hierarchical requests

TODO: Think about how we can reuse the existing badger storage inside the blockstore implementation, to avoid having to store a duplicate copy of the data in every state diff (one version in the blockstore, and another version of each of the entities in the state diff in the badger storage).
* Can we add an API to the Storage interfaces to query for data by hash instead of by ID? Currently data in badger is keyed by flow ID, but perhaps there's a way to add a Secondary key?
* We may be able to implement this secondary index ourselves: https://github.com/dgraph-io/badger/issues/738#issuecomment-496704883
    * Add a second db that maps from the hash to the flow ID.

Can we do the same for state checkpoints as well?

**Comment by peterargue** [comment]
After discussion, we are not going to attempt to reuse the existing WAL datastore for the blockstore since there are consistency challenges we don't want to take on now. For now, we'll create a new datastore and store the blocks separately

**Comment by smnzhu** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Flow-Protocol-5a2ad022cee40e25b0885f82/issues/onflow/flow-go/1450?planning-poker) with ZenHub @franklywatson @m4ksio @peterargue @vishalchangrani

**Comment by peterargue** [comment]
After further investigation, we will implement a [BlockService](https://github.com/ipfs/go-blockservice/blob/master/blockservice.go). Under the covers, we'll need a datastore that supports badger and a default TTL.

The blockservice uses the `v0.5.0` `Datastore` interface that includes contexts. That update hasn't been implemented for  the badger `v2` datastore implementation, so I've submitted a PR to add it: `https://github.com/ipfs/go-ds-badger2/pull/49`

**Comment by peterargue** [comment]
After some work on this, we've decided to submit our changes to the `go-ds-badger2` repo directly: `https://github.com/ipfs/go-ds-badger2/pull/50`

**Comment by peterargue** [comment]
https://github.com/ipfs/go-ds-badger2/pull/50 is merged.

I'm waiting for protocol labs to tag the commit, but in the meantime we can pull it in with
```
go get github.com/ipfs/go-ds-badger2@2bc0150
```

Here's the diff (based off `smnzhu/state-requester` from https://github.com/onflow/flow-go/pull/1582
```
diff --git a/go.mod b/go.mod
index 15c532ae9..88443b3a0 100644
--- a/go.mod
+++ b/go.mod
@@ -11,7 +11,7 @@ require (
        github.com/btcsuite/btcd v0.21.0-beta
        github.com/dapperlabs/testingdock v0.4.2
        github.com/davecgh/go-spew v1.1.1
-       github.com/dgraph-io/badger/v2 v2.0.3
+       github.com/dgraph-io/badger/v2 v2.2007.3
        github.com/ef-ds/deque v1.0.4
        github.com/ethereum/go-ethereum v1.9.13
        github.com/fsnotify/fsnotify v1.5.1 // indirect
@@ -36,6 +36,7 @@ require (
        github.com/ipfs/go-blockservice v0.2.0
        github.com/ipfs/go-cid v0.1.0
        github.com/ipfs/go-datastore v0.5.0
+       github.com/ipfs/go-ds-badger2 v0.1.2-0.20211126133957-2bc0150c7534 // indirect
        github.com/ipfs/go-ipfs-blockstore v0.2.0
        github.com/ipfs/go-ipfs-provider v0.7.0
        github.com/ipfs/go-log v1.0.5
diff --git a/go.sum b/go.sum
index 4d14cc778..d6e0a28ad 100644
--- a/go.sum
+++ b/go.sum
@@ -261,9 +261,13 @@ github.com/dgraph-io/badger v1.6.2 h1:mNw0qs90GVgGGWylh0umH5iag1j6n/PeJtNvL6KY/x
 github.com/dgraph-io/badger v1.6.2/go.mod h1:JW2yswe3V058sS0kZ2h/AXeDSqFjxnZcRrVH//y2UQE=
 github.com/dgraph-io/badger/v2 v2.0.3 h1:inzdf6VF/NZ+tJ8RwwYMjJMvsOALTHYdozn0qSl6XJI=
 github.com/dgraph-io/badger/v2 v2.0.3/go.mod h1:3KY8+bsP8wI0OEnQJAKpd4wIJW/Mm32yw2j/9FUVnIM=
+github.com/dgraph-io/badger/v2 v2.2007.3 h1:Sl9tQWz92WCbVSe8pj04Tkqlm2boW+KAxd+XSs58SQI=
+github.com/dgraph-io/badger/v2 v2.2007.3/go.mod h1:26P/7fbL4kUZVEVKLAKXkBXKOydDmM2p1e+NhhnBCAE=
 github.com/dgraph-io/ristretto v0.0.2-0.20200115201040-8f368f2f2ab3/go.mod h1:KPxhHT9ZxKefz+PCeOGsrHpl1qZ7i70dGTu2u+Ahh6E=
 github.com/dgraph-io/ristretto v0.0.2 h1:a5WaUrDa0qm0YrAAS1tUykT5El3kt62KNZZeMxQn3po=
 github.com/dgraph-io/ristretto v0.0.2/go.mod h1:KPxhHT9ZxKefz+PCeOGsrHpl1qZ7i70dGTu2u+Ahh6E=
+github.com/dgraph-io/ristretto v0.0.3-0.20200630154024-f66de99634de h1:t0UHb5vdojIDUqktM6+xJAfScFBsVpXZmqC9dsgJmeA=
+github.com/dgraph-io/ristretto v0.0.3-0.20200630154024-f66de99634de/go.mod h1:KPxhHT9ZxKefz+PCeOGsrHpl1qZ7i70dGTu2u+Ahh6E=
 github.com/dgrijalva/jwt-go v3.2.0+incompatible/go.mod h1:E3ru+11k8xSBh+hMPgOLZmtrrCbhqsmaPHjLKYnJCaQ=
 github.com/dgryski/go-farm v0.0.0-20190104051053-3adb47b1fb0f/go.mod h1:SqUrOPUnsFjfmXRMNPybcSiG0BgUW2AuFH8PAnS2iTw=
 github.com/dgryski/go-farm v0.0.0-20190423205320-6a90982ecee2 h1:tdlZCpZ/P9DhczCTSixgIKmwPv6+wP5DGjqLYw5SUiA=
@@ -601,6 +605,8 @@ github.com/ipfs/go-ds-badger v0.0.7/go.mod h1:qt0/fWzZDoPW6jpQeqUjR5kBfhDNB65jd9
 github.com/ipfs/go-ds-badger v0.2.1/go.mod h1:Tx7l3aTph3FMFrRS838dcSJh+jjA7cX9DrGVwx/NOwE=
 github.com/ipfs/go-ds-badger v0.2.3/go.mod h1:pEYw0rgg3FIrywKKnL+Snr+w/LjJZVMTBRn4FS6UHUk=
 github.com/ipfs/go-ds-badger v0.2.7/go.mod h1:02rnztVKA4aZwDuaRPTf8mpqcKmXP7mLl6JPxd14JHA=
+github.com/ipfs/go-ds-badger2 v0.1.2-0.20211126133957-2bc0150c7534 h1:kxyTnBEBcNY/E/vXNitarHWS/5w7LWKN/+vDuf2tOT4=
+github.com/ipfs/go-ds-badger2 v0.1.2-0.20211126133957-2bc0150c7534/go.mod h1:wD65qQCjB35uNOHaaha+tudGVWegJ7dFuFKY+3iJKjk=
 github.com/ipfs/go-ds-leveldb v0.0.1/go.mod h1:feO8V3kubwsEF22n0YRQCffeb79OOYIykR4L04tMOYc=
 github.com/ipfs/go-ds-leveldb v0.1.0/go.mod h1:hqAW8y4bwX5LWcCtku2rFNX3vjDZCy5LZCg+cSZvYb8=
 github.com/ipfs/go-ds-leveldb v0.4.1/go.mod h1:jpbku/YqBSsBc1qgME8BkWS4AxzF2cEu1Ii2r79Hh9s=
```

**Comment by peterargue** [comment]
Here's the recommended way to instantiate for our usecase
```
import (
	"github.com/dgraph-io/badger/v2/options"
	badgerds "github.com/ipfs/go-ds-badger2"
)
opts := badgerds.DefaultOptions.
	WithTTL(15 * time.Minute)
opts.Options = opts.
	WithCompression(options.None)

ds, err := badgerds.NewDatastore(dsDir, &opts)
```
