### ISSUE TITLE
[State sync engine] Push channel for state diffs

### ISSUE THREAD

**Issue by smnzhu** [onflow/flow-go#1453]
Consider a separate push channel for state diff hashes for latency reasons, and an eager state requester engine that requests state diff blocks based on this push channel.
- We could get this for free if we add the state diff hash to ExecutionResult, since execution results are pushed to AN's already: https://github.com/onflow/flow-go/blob/c5fc8ac76879b8427a592bdf9f45b62698d36e43/engine/access/ingestion/engine.go#L111
- If we implement this, we need to track the hashes of the state diffs that were eagerly requested, and the normal state requester engine should later verify these once the block containing those execution results is sealed. If the state diff hashes in the sealed block don't match what we originally requested, we should invalidate the previous downloaded blocks and start a new request.

**Comment by smnzhu** [comment]
> I suspect this is about a logic that downloads the execution data before incoporation and sealing, as soon as it's available (through receipt broadcast)?

Yes, and my point in that sentence is that since we cannot be sure at that point that the execution data is correct, we need to check the hash again once it is actually sealed.

**Comment by peterargue** [comment]
@smnzhu is this still needed?
