### ISSUE TITLE
[State sync protocol] Execution Data Fetcher

### ISSUE THREAD

**Issue by smnzhu** [onflow/flow-go#1626]
We should encapsulate the logic for requesting an entire Execution Data given the root CID into a `ExecutionDataFetcher` component. This component can be used by the ExecutionDataRequester engine.

The component should leverage Bitswap sessions.

This includes writing unit tests.

**Comment by smnzhu** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Flow-Protocol-5a2ad022cee40e25b0885f82/issues/onflow/flow-go/1626?planning-poker) with ZenHub @franklywatson @m4ksio @peterargue @vishalchangrani

**Comment by peterargue** [comment]
@smnzhu is this still needed now that we're using blockservice?

**Comment by smnzhu** [comment]
This was tracking the implementation of ExecutionDataService, which is now finished
