### ISSUE TITLE
[Execution state] - providing an API for exists and sizes 

### ISSUE THREAD

**Issue by ramtinms** [onflow/flow-go#1751]
FVM needs to call exists and sizes during its operation (e.g. when computing storage used changes). This is currently happening by a full read of value which might be expensive due to the deep copy of the payload.

**Comment by fxamacker** [comment]
Maybe `Forest.Proofs()` can also benefit from exists. 

`Forest.Proofs()` calls `Forest.Read()` to find all not-found paths.  Returned payloads from `Forest.Read()` are not used except to check whether it's empty.

**Comment by fxamacker** [comment]
Based on chat with @ramtinms, we don't need `Exists` for now because we can just use `ValueSizes`.  `ValueSizes` returns value size (not payload size), so it doesn't include key size.
