### ISSUE TITLE
Mainnet 4 access node is in a crash loop

### ISSUE THREAD

**Issue by vishalchangrani** [onflow/flow-go#1767]
## 🐞 Bug Report

Mainnet 4 access node 1 is in a crash loop:
> Dec 13 18:16:49 access-001 docker[3992485]: panic: runtime error: index out of range [-1]
> Dec 13 18:16:49 access-001 docker[3992485]: goroutine 15809 [running]:
> Dec 13 18:16:49 access-001 docker[3992485]: github.com/onflow/flow-go/engine/access/rpc/backend.(*backendEvents).getBlockEventsFromExecutionNode(0xc01b3555c8, 0x18ab200, 0xc022b60870, 0xc0166b5a20, 0x0, 0x0, 0xc022b5e630, 0x23, 0x14be760, 0xc022311f80, ...)
> Dec 13 18:16:49 access-001 docker[3992485]:         /app/engine/access/rpc/backend/backend_events.go:107 +0xa31
> Dec 13 18:16:49 access-001 docker[3992485]: github.com/onflow/flow-go/engine/access/rpc/backend.(*backendEvents).GetEventsForHeightRange(0xc01b3555c8, 0x18ab200, 0xc022b60870, 0xc022b5e630, 0x23, 0x144e251, 0xb776ca, 0x0, 0x0, 0x0, ...)
> Dec 13 18:16:49 access-001 docker[3992485]:         /app/engine/access/rpc/backend/backend_events.go:65 +0x428
> Dec 13 18:16:49 access-001 docker[3992485]: github.com/onflow/flow-go/access.(*Handler).GetEventsForHeightRange(0xc015f3d6e0, 0x18ab200, 0xc022b60870, 0xc022311f80, 0xc015f3d6e0, 0x0, 0xc016617b58)
> Dec 13 18:16:49 access-001 docker[3992485]:         /app/access/handler.go:364 +0xca
> Dec 13 18:16:49 access-001 docker[3992485]: github.com/onflow/flow/protobuf/go/flow/access._AccessAPI_GetEventsForHeightRange_Handler(0x1522ac0, 0xc015f3d6e0, 0x18ab200, 0xc022b60870, 0xc022b9a120, 0x0, 0x18ab200, 0xc022b60870, 0xc022b5e600, 0x2f)
> Dec 13 18:16:49 access-001 docker[3992485]:         /go/pkg/mod/github.com/onflow/flow/protobuf/go/flow@v0.1.8/access/access.pb.go:2161 +0x217
> Dec 13 18:16:49 access-001 docker[3992485]: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00001a540, 0x18bcd40, 0xc0165e4480, 0xc01e104a00, 0xc015f46a20, 0x2288338, 0x0, 0x0, 0x0)
> Dec 13 18:16:49 access-001 docker[3992485]:         /go/pkg/mod/google.golang.org/grpc@v1.31.1/server.go:1180 +0x4fd
> Dec 13 18:16:49 access-001 docker[3992485]: google.golang.org/grpc.(*Server).handleStream(0xc00001a540, 0x18bcd40, 0xc0165e4480, 0xc01e104a00, 0x0)
> Dec 13 18:16:49 access-001 docker[3992485]:         /go/pkg/mod/google.golang.org/grpc@v1.31.1/server.go:1503 +0xd57
> Dec 13 18:16:49 access-001 docker[3992485]: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0134df480, 0xc00001a540, 0x18bcd40, 0xc0165e4480, 0xc01e104a00)
> Dec 13 18:16:49 access-001 docker[3992485]:         /go/pkg/mod/google.golang.org/grpc@v1.31.1/server.go:843 +0xbb
> Dec 13 18:16:49 access-001 docker[3992485]: created by google.golang.org/grpc.(*Server).serveStreams.func1
> Dec 13 18:16:49 access-001 docker[3992485]:         /go/pkg/mod/google.golang.org/grpc@v1.31.1/server.go:841 +0x204
> Dec 13 18:16:49 access-001 systemd[1]: flow-access.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
> Dec 13 18:16:49 access-001 systemd[1]: flow-access.service: Failed with result 'exit-code'.

## What is the severity of this bug?

**Important**

**Critical - Urgent:** We can't do anything if this isn't actioned immediately (product doesn't function without this, it's blocking us or users, or it resolves a high severity security issue). Whole team should drop what they're doing and work on this. 

**Critical:** We can't do anything if this isn't actioned immediately (product doesn't function without this, it's blocking us or users, or it resolves a high severity security issue). One person should look at this right now. 

**Important:** * We have to do this before we ship, but it can wait until the next sprint (product or feature won't function without it, but it's not blocking us or users right now). Team should do this in the next sprint.

**Should have:** * It would be better if we do this before we ship, but it's OK if we don't (product functions without this, but it's a better user experience). Consider adding to a future sprint.

**Could have:** It really doesn't matter if we do this (product functions without this, impact to user is minimal). 

## Reproduction steps

Steps to reproduce the behaviour:

1. Make API call '...'
1. See error

- [ ] I followed these steps and was able to reproduce the issue

## Specifications

- System: (e.g. macOS 10.13.4, Linux)
- Go: (e.g. 1.13)

**Comment by franklywatson** [comment]
Not something we're seeing anymore
