### ISSUE TITLE
[Merkle'ized Event Proofs] Revise Payload trie to allow for safe inclusion proofs

### ISSUE THREAD

**Issue by AlexHentschel** [onflow/flow-go#1786]
At the moment, our [`merkle.Tree`](https://github.com/onflow/flow-go/blob/d69930a2472c99c7e51e58155a0de46022b267e7/storage/merkle/tree.go) is geared to provide a set commitment for an _entire_ set. However, it is not safe for inclusion / exclusion proofs of _individual_ elements. Furthermore, the trie is not safe for storing elements with different key lengths, but the API does not reflect this limitation and the implementation does not check.

### Goal: 
* update the trie's graph structure to support safe inclusion and exclusion proofs
* add safety checks to enforce consistent key length

**Comment by AlexHentschel** [comment]
implemented by PR https://github.com/onflow/flow-go/pull/1800

**Comment by tarakby** [comment]
I guess we can close this issue? @AlexHentschel
