### ISSUE TITLE
Running "make test" fails

### ISSUE THREAD

**Issue by rexposadas** [onflow/flow-go#1798]
## Problem Definition

Running `make test` in the master branch always produces an error similar to this: 

`    --- FAIL: TestTopologyTestSuite/TestHighScaleLinearFanout (0.99s)
        testUtil.go:354:
                Error Trace:    testUtil.go:354
                                                        testUtil.go:119
                                                        topology_test.go:141
                                                        topology_test.go:178
                                                        topology_test.go:115
                Error:          Received unexpected error:
                                could not create libp2p host: failed to listen on any addresses: [listen tcp4 0.0.0.0:0: socket: too many open files
]`

## Definition of Done

What tests must pass for this issue to be considered solved?

All tests should pass. 

My expectations is that a newly forked project should pass "make test".  I do see this issue of test flakiness: https://github.com/onflow/flow-go/issues/1176

But I have not been able to get the test running, even on multiple tries.   I assume i'm doing something wrong. How is everyone able to get "make test" to pass? Are there config settings I need to make in my machine?

**Comment by peterargue** [comment]
I haven't run into that issue before with `make test`, but the error message `too many open files` typically means you need to increase your `ulimit`. 

Try running `ulimit -n` to see what it's set to now. To set a reasonable limit, try `ulimit -n 4096`

**Comment by tehranifar** [comment]
Thanks @peterargue the fix worked for me. `4096` was still too small, increased to `64000`.

**Comment by rexposadas** [comment]
Thanks for that @peterargue
