### ISSUE TITLE
Why do collection nodes slowly raise from 30% to 75% CPU with constant input TPS?

### ISSUE THREAD

**Issue by simonhf** [onflow/flow-go#1927]
## Problem Definition

When testing using the loader in feedback mode at 260 TPS on localnet with 14 nodes incl. 3 collection clusters for 1,800 seconds on a 16 CPU core benchnet dev box, using TPS x30 accounts, and max. 200 transactions per collection [1], the collection nodes are the only nodes which continuously increase CPU for the first ~ 900 seconds, from about 30% to 75% CPU.

None of the other nodes increase CPU usage at constant TPS load.

[1] https://www.notion.so/dapperlabs/Test-feedback-loader-for-account-exhaustion-52a3f9deb65247f9841ed140a558aaac

## Proposed Solution

TBD

## Definition of Done

The aim of this issue is to investigate and discover why this happens with collection nodes.

**Comment by Kay-Zee** [comment]
Likely due to a backlog of tx's in the mempool that need to be checked against.

This could be due to the just more and more tx's that new transactions need to be checked against for duplication.
