### ISSUE TITLE
Why can output TPS drop by 8% for some minutes after many minutes of stable TPS?

### ISSUE THREAD

**Issue by simonhf** [onflow/flow-go#1928]
## Problem Definition

When testing using the loader in feedback mode at 260 TPS on localnet with 14 nodes incl. 3 collection clusters for 1,800 seconds on a 16 CPU core benchnet dev box, using TPS x30 accounts, and max. 200 transactions per collection [1], the average output TPS per 60 seconds remains around 260 TPS for 10 minutes, but then drops mysteriously to ~ 240 TPS for 3 minutes.

The following report illustrates the issue and the 3 minutes of lower TPS are marked.

Explanation of report:
* The 1st column shows the difference in backlog between the input TPS and output TPS AKA finalized transactions.
* When the backlog becomes too high then the loader in feedback mode is subjected to account exhaustion.
* The columns to the left of the log second time stamp shows the input TPS and 0%, 50%, 90%, & 100% percentiles RE eventual seconds until transaction finalization.
* The columns to the right of the log second time stamp shows the output TPS and 0%, 50%, 90%, & 100% percentiles RE seconds since transaction input until now / finalization.
* The 'avg TPS` column shows the average output TPS for the last 60 log seconds.

```
+2843; 260 .. 260  9.2  9.2  9.2  9.2 -> 2022-01-28T23:49:45 <- 272  9.2  9.2  9.2  9.2 # 250 avg TPS last 60s
+2920; 260 .. 260  9.1  9.2 10.2 12.1 -> 2022-01-28T23:50:45 <- 248  8.2  9.2 10.2 10.2 # 258 avg TPS last 60s
+3060; 260 .. 260  9.2  9.2  9.2 13.3 -> 2022-01-28T23:51:45 <- 155  9.2  9.2  9.4 14.4 # 257 avg TPS last 60s
+3043; 260 .. 260  9.2 10.2 10.2 12.2 -> 2022-01-28T23:52:45 <- 173  9.3 10.2 10.3 12.2 # 260 avg TPS last 60s
+3132; 260 .. 260  9.2 10.2 10.2 13.2 -> 2022-01-28T23:53:45 <-  81 10.3 10.3 10.3 11.3 # 258 avg TPS last 60s
+3221; 260 .. 260  9.4 10.4 10.4 15.2 -> 2022-01-28T23:54:45 <- 163  9.2 10.1 10.2 10.2 # 258 avg TPS last 60s
+3224; 260 .. 260  9.5  9.6 10.5 13.4 -> 2022-01-28T23:55:45 <- 109 10.3 10.3 16.3 17.3 # 259 avg TPS last 60s
+3325; 260 .. 260  9.2  9.2 10.2 10.2 -> 2022-01-28T23:56:45 <- 102 10.2 10.2 10.2 10.2 # 258 avg TPS last 60s
+3419; 260 .. 260 10.2 12.2 14.3 14.3 -> 2022-01-28T23:57:45 <- 247 10.2 10.2 11.2 12.2 # 258 avg TPS last 60s
+3224; 260 .. 260  9.4 11.1 14.3 15.2 -> 2022-01-28T23:58:45 <- 249 10.1 10.2 11.2 11.2 # 263 avg TPS last 60s
<start of lower average output TPS>
+4559; 260 .. 260 15.4 20.5 25.7 25.7 -> 2022-01-28T23:59:45 <-   0  0.0  0.0  0.0  0.0 # 237 avg TPS last 60s
+5842; 260 .. 260 20.7 24.2 31.3 31.3 -> 2022-01-29T00:00:45 <- 600 17.0 20.0 23.0 31.9 # 236 avg TPS last 60s
+6796; 260 .. 260 27.6 27.6 32.3 32.3 -> 2022-01-29T00:01:46 <- 200 23.3 24.3 25.3 36.3 # 240 avg TPS last 60s
<end of lower average output TPS>
+6120; 260 .. 260 19.8 22.9 34.6 34.6 -> 2022-01-29T00:02:48 <- 200 18.3 19.3 20.3 20.3 # 256 avg TPS last 60s
+514;    0 ..   0  0.0  0.0  0.0  0.0 -> 2022-01-29T00:04:05 <- 972 28.3 34.3 38.3 49.3 # 293 avg TPS last 60s
```

Apart from the average output TPS per 60 seconds dipping, the output TPS per log second often shows __zero__ finalizations later on in the load test:
* Here are 15 log seconds but only 6 of them have a total of 2,800 finalized transactions.
* 2,800 transactions over 15 seconds is 186.6 average finalized transactions per second. Much lower than the expected 260.

```
$ less ../../../run-200-col-n14-tps-260-sec-900-fb1-acc-x30/run-800-copy-logs.sh.in-out-tps.txt
...
+6360; 260 .. 260 23.4 24.8 40.5  40.5 -> 2022-01-29T00:02:42 <-   0  0.0  0.0  0.0   0.0
+6620; 260 .. 260 22.3 27.9 39.5  39.6 -> 2022-01-29T00:02:43 <-   0  0.0  0.0  0.0   0.0
+5880; 260 .. 260 22.8 26.9 38.5  38.5 -> 2022-01-29T00:02:44 <- 1000 21.7 24.7 26.7  29.7
+5940; 260 .. 260 21.8 25.9 37.5  37.5 -> 2022-01-29T00:02:45 <- 200 20.3 21.3 22.3  23.3
+6000; 260 .. 260 20.8 24.9 36.5  36.6 -> 2022-01-29T00:02:46 <- 200 21.9 22.9 23.9  23.9
+6060; 260 .. 260 20.8 23.9 35.6  35.6 -> 2022-01-29T00:02:47 <- 200 19.6 20.6 21.6  21.6
+6120; 260 .. 260 19.8 22.9 34.6  34.6 -> 2022-01-29T00:02:48 <- 200 18.3 19.3 20.3  20.3
+6380; 260 .. 260 21.9 24.2 33.5  33.6 -> 2022-01-29T00:02:49 <-   0  0.0  0.0  0.0   0.0
+6640; 260 .. 260 20.9 32.5 32.6  32.6 -> 2022-01-29T00:02:50 <-   0  0.0  0.0  0.0   0.0
+6900; 260 .. 260 22.2 31.5 31.5  32.8 -> 2022-01-29T00:02:51 <-   0  0.0  0.0  0.0   0.0
+7160; 260 .. 260 21.2 30.5 31.8  31.8 -> 2022-01-29T00:02:52 <-   0  0.0  0.0  0.0   0.0
+7420; 260 .. 260 20.2 29.5 30.8  30.8 -> 2022-01-29T00:02:53 <-   0  0.0  0.0  0.0   0.0
+7680; 260 .. 260 19.2 28.5 30.8  30.8 -> 2022-01-29T00:02:54 <-   0  0.0  0.0  0.0   0.0
+6800; 120 .. 120 18.2 27.5 29.8  29.8 -> 2022-01-29T00:02:55 <- 1000 22.4 27.5 32.4  36.4
+6835;  35 ..  35 19.3 26.6 28.8  28.8 -> 2022-01-29T00:02:56 <-   0  0.0  0.0  0.0   0.0
...
```

[1] https://www.notion.so/dapperlabs/Test-feedback-loader-for-account-exhaustion-52a3f9deb65247f9841ed140a558aaac

## Proposed Solution

TBD

## Definition of Done

The aim of this issue is to investigate and discover why the avg TPS per 60 seconds dips down for so long after so many minutes of load.

Why is this important? An average of -20 output TPS for ~ 180 seconds, but continued 260 TPS input, causes a backlog of several thousand transactions. This causes account exhaustion in the loader running with feedback mode.

**Comment by Kay-Zee** [comment]
For the line at the beginning of the slow down, we see:

```
+4559; 260 .. 260 15.4 20.5 25.7 25.7 -> 2022-01-28T23:59:45 <-   0  0.0  0.0  0.0  0.0 # 237 avg TPS last 60s
```

meaning there was zero blocks in that second. So it means a block was delayed, either due to execution slow-ness, or consensus slow-ness. We'll have to determine which one it is.
