### ISSUE TITLE
Define Protocol API for Access Node / Observer Service

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-go#1990]
We need to reach an agreed upon formal specification for the Protocol API that will respond to upstream requests from the Flow Access API Service. 

### Definition of done

- [ ] Figure out what subset of the Access API we want to use for the protocol API

**Comment by franklywatson** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/flow-access-pod-61f34bab7683880018d2cf42/issues/onflow/flow-go/1990?planning-poker) with ZenHub @m4ksio @peterargue @smnzhu @vishalchangrani

**Comment by koko1123** [comment]
Defined and documented in this epic: https://github.com/onflow/flow-go/issues/2425
