### ISSUE TITLE
Define State Streamer and Registration service

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-go#1991]
We need to reach an agreed upon formal specification for the State Streamer Consumer and the Registration and provider API which is how the DPS will remain in sync with the upstream protocol and execution state that originates from the Consensus Follower and Execution State Sync mechanism

### Definition of done

- [ ] The interoperability mechanism for the stream consumer and stream registration is fully specified in terms of functions, inputs, outputs, errors returned and model entities - assuming swagger or something like that
- [ ] Documentation for the specification is complete

**Comment by franklywatson** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/flow-access-pod-61f34bab7683880018d2cf42/issues/onflow/flow-go/1991?planning-poker) with ZenHub @smnzhu @peterargue @m4ksio @vishalchangrani

**Comment by koko1123** [comment]
related to #2465 and #2466
