### ISSUE TITLE
Update reporters to use runtime, add tests

### ISSUE THREAD

**Issue by turbolent** [onflow/flow-go#2002]
## Problem Definition

The reporters are currently broken and need to be updated

- Account reporter
- Balance reporter

Also, it would be beneficial to add tests, so that breakage due to e.g. Cadence behaviour changes are detected early.

## Proposed Solution

- Instead of reading from the state/ledger directly, make the reads future-proof by using a maintained API, i.e. Cadence's `Runtime.ReadStored` function (https://github.com/onflow/cadence/blob/3d29437ac69602c7a96dc508681fedf119888f35/runtime/runtime.go#L98-L100)

## Definition of Done

- Reporters work again
- Tests ensure reporters work

**Comment by ramtinms** [comment]
Update: we identified that account reporter has no issue, there was an issue with the migration itself, 
but for balance reporter, we need to change the way we check all the objects and match expected types. 

For this goal I suggest we iterate over accounts, call GetStorageMap, iterate over items, check for the expected type (in this context Flow Vault type) and recursively do the call for children that are array or maps.
