### ISSUE TITLE
Expose missing fields from flow.Header in GetBlockHeaderByID API response

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-go#2044]
## Problem Definition

A request was made from a key partner to include the missing fields on flow.Header into GetBlockHeaderByID API response since they are needed. This is needed for the partner launch

## Definition of Done

* Fields referred to in this issue have been added to the API response from the flow.Header and are checked for in corresponding tests

Expose following fields from `flow.Header` in the GetBlockHeaderByID API response:
```ParentVoterIDs     []Identifier
ParentVoterSigData []byte
ProposerID         Identifier
ProposerSigData    []byte
View               uint64
```

**Comment by koko1123** [comment]
Done, fixed with all other response conversions
