### ISSUE TITLE
Update Observer's Access API to proxy to downstream Access Node

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-go#2065]
## Problem Definition

Currently, the Observer service runs the standard Access API, which forwards requests to staked Collection/Execution Nodes. However, the observer should only interact with its configured staked Access Node for access as its gateway into the network.

## Proposed Solution

Update the Access API used by the observer to proxy requests to its configured staked Access Node, instead of sending requests directly to other staked nodes.

## Definition of Done

The observer service communicates only with its configured Access Node to serve all Access API requests.

## Depends On
* https://github.com/onflow/flow-go/issues/2064

**Comment by smnzhu** [comment]
Highlighting the specific APIs that are relevant here:

* SendTransaction
* GetTransaction
* GetTransactionResult
* GetCollection
* ExecuteScript
* GetAccount
* GetEvents

Not 100% sure this covers it, but off the top of my head

**Comment by vishalchangrani** [comment]
Closing this since this has now been implemented
