### ISSUE TITLE
Implement integration tests for running the Observer service as a standalone node

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-go#2067]
## Problem Definition

Currently, there are integration tests that cover the consensus follower library [here](https://github.com/onflow/flow-go/blob/master/integration/tests/access/unstaked.go). Now that the Observer can run as a stand alone application, we need tests that also cover that usecase.

## Proposed Solution

Write integration tests that cover the interactions between the observer service and access node to ensure following consensus works as expected.

## Definition of Done

There are integration tests that cover:
* Observers following consensus from a downstream Access Node

## Depends On
* https://github.com/onflow/flow-go/issues/2063

**Comment by smnzhu** [comment]
In addition, we should update the unstaked access node integration tests to use the standalone instead of the consensus follower library

**Comment by AliSMAmin** [comment]
https://github.com/GetElastech/flow-go/pull/4

**Comment by AliSMAmin** [comment]
Completed by https://github.com/onflow/flow-go/pull/2554
