### ISSUE TITLE
[Access API] Add block_id and transaction_index to GetTransactionResult parameters to avoid duplicate transaction hashes

### ISSUE THREAD

**Issue by koko1123** [onflow/flow-go#2100]
## Problem Definition

In engine/access/rpc/backend/backend_transactions.go, when looking up a transaction result for a particular transaction hash, the Access Node does:
`block, err := b.lookupBlock(txID)`
This block then gets used to query the Execution Node for a particular transaction result within a specific block.
Since users can seemingly resubmit the same transaction (with the same transaction hash) multiple times in different blocks, the Access Node finds a previous block with the same transaction hash when it does the lookupBlock(txID), and thus the wrong transaction result gets returned

## Proposed Solution

Define a new endpoint `GetTransactionResultByIndex` which takes in block_id and transaction_index parameters, where transaction_index represents the index within the block (not within a collection). Both of these are required to guarantee unambiguity. We will then also need to add the `GetTransactionResultByIndex` API to the ExecutionAPI, and the Access node handler should forward the request to the execution node.

**Comment by smnzhu** [comment]
@koko1123 Updated the Proposed Solution, please review it again.

Also, we probably want to create a separate issue for the `flow-go-sdk` to support this new endpoint.

**Comment by koko1123** [comment]
As we have implemented the EN side of these changes we've encountered a constraint:

1. Transactions are currently stored and indexed in ANs by `TransactionId`, not by `blockId` and `index`
2. As the status of the transaction in same `transactionId` at the inter/intra block level, the indexed status stored will reflect the *most recent* status, instead of the status at the exact block/index
3. This means that we do not have accurate data for previous sporks at the AN level
4. We are implementing the indexing scheme in 1., that will track this for future sporks
5. for mainnet16 and 15, we'll have to backfill transaction data for this new store, which we can attend to later.

**Comment by m4ksio** [comment]
> As we have implemented the EN side of these changes we've encountered a constraint:
> 
> 1. Transactions are currently stored and indexed in ANs by `TransactionId`, not by `blockId` and `index`

That is not correct, I might have mislead you earlier. We key both transactions results by blockID and txID. So this cover duplicated txs in different blocks, only failing when we have two txs in same block.
For events we are in a better position, as we key events by blockID, txID txIndex (and event index) - which means we can query events without a miss.

I think we might be able to regenerate the index for tx results unless we have two txs in one block, but that should be easy to check

**Comment by bluesign** [comment]
Sorry I read the problem definition, but for me it is working as intended, can someone clarify where is the problem here? 

Or is there a case it can get result from newer block?

**Comment by bluesign** [comment]
Does this break events? If so can have security implications I guess
