### ISSUE TITLE
[State Sync] Verification of Execution Data ID

### ISSUE THREAD

**Issue by smnzhu** [onflow/flow-go#2120]
Verification nodes need to verify the new ExecutionDataID field of each Chunk. 

They can do this by re-creating the [ExecutionData](https://github.com/onflow/flow-go/blob/056778a614495ae104264022a3d5f0ae8999c666/module/state_synchronization/execution_data.go) for the chunk, and then compute the ID using [ExecutionDataService.Add](https://github.com/onflow/flow-go/blob/d7f1d04b194ec6275d32430bcd28182514a8c5f2/module/state_synchronization/execution_data_service.go#L191).

For now, we don't really need verification nodes to actually store the blobs to the BlobService, so we can just [instantiate](https://github.com/onflow/flow-go/blob/d7f1d04b194ec6275d32430bcd28182514a8c5f2/module/state_synchronization/execution_data_service.go#L53) the ExecutionDataService with a stub BlobService implementation for which all the methods are just noops.

**Comment by m4ksio** [comment]
https://github.com/onflow/flow-go/pull/2647
