### ISSUE TITLE
[State Sync] Implementing Execution Data expiration for Access Nodes

### ISSUE THREAD

**Issue by synzhu** [onflow/flow-go#2130]
We need a mechanism for Access Nodes to expire and purge Execution Data from their blobstores.

We currently do time-based expiry for execution nodes, which is okay because Execution Nodes are the producers of the data.

However, there are edge cases that could cause problems if we use the same approach for Access Nodes. If an Access Node gets stuck trying to download the Execution Data for a particular height `h` from the network, but it successfully downloads the subsequent ones, then by the time it finally succeeds for height `h`, the Execution Data it previously download for the subsequent heights may have already expired.

Some options:
* Set a limit on how far past the lowest pending height that we download Execution Data for. In other words, if we get stuck on a certain height `h`, then we will download Execution Data up to at most `h + n` before we must stop and wait for `h` to be successfully downloaded. 
  * With this approach, we would need to implement explicit height-based expiration mechanism, and when we expire a blob tree we need to be careful not to delete any blobs that may also belong to other blob trees. 
  * Alternatively, we could just optimistically delete all the blobs in the blob tree. If we later notice that a blob is missing from a blob tree that should have already been downloaded, then we just try to download it again.
* If we continue to use the time-based expiration, then the Requester needs to have additional logic to handle the case that by the time an Execution Data for a given height is ready to be notified, it is actually no longer available from badger because it has expired. That height then needs to be requeued for download.

Imo we should go with the first approach, because the second approach sacrifices the performance of our own node for the benefit of other nodes on the network, and it's unclear the actual extent of this benefit in practice.

NOTE: Even for execution nodes, the time-based expiration may be a problem because the Blockstore implementation always checks the existence of a key before Putting it: https://github.com/ipfs/go-ipfs-blockstore/blob/f51f67c96f78bc0b7bd21dc1e01a61ebdf20a462/blockstore.go#L174-L178

This means when adding a new Execution Data blob tree to the blob store, if any blob in that blob tree is already present in the blob store because it was also part of an earlier blob tree, then the expiration for that blob wouldn't get updated. Therefore, that blob would end up expiring earlier than it should.

A simple way to workaround this is to create a thin wrapper around the Blockstore implementation that overrides the `Put` and `PutMany` methods and skips the `Has` check.

**Comment by peterargue** [comment]
I think option 1 makes sense, but also that `n` should be large.

> Imo we should go with the first approach, because the second approach sacrifices the performance of our own node for the benefit of other nodes on the network, and it's unclear the actual extent of this benefit in practice.

I agree with the approach, but I disagree with the reasoning. I think we should optimize for network health, and in the sync case that means maximizing the number of nodes seeding each blob as that spreads the network load across more participants and reduces the risk of lost blobs. Eventually, we'll have better options for managing checkpointing and optimized catchup. 

A couple alternative options:

3. Set a limit on the amount of data that can be used for execution data. Adding data beyond this causes older data to be purged. I think this would be the most natural for operators.
4. Set a limit on the number of blocks stored. When the limit is exceeded, older blocks are purged. 

In both cases, if there is a stuck height that is far behind, option 1 kicks in to limit additional downloads. The defaults should be picked such that there's plenty of buffer so it's extremely unlikely to reach the limit.

My preference would be a total size limit, plus option 1 to manage cases where the node gets stuck on a block for a long time.  I think node operators would want to put a size limit on the total disk space used for execution data, and we should try to align the limits to maximize the use of that space to seed as much data to other nodes on the network as possible.

**Comment by smnzhu** [comment]
Another possibility is that we can maybe take advantage of badger User Metadata for keys: https://pkg.go.dev/github.com/dgraph-io/badger#:~:text=value%206%20encoded-,Setting%20Time%20To%[…]20Metadata%20on%20Keys,-Badger%20allows%20setting

For each CID, we would set the metadata to track the *most recent* blob tree that this blob appeared in.

Then, when we expire a blob tree, we only delete the blobs for which the metadata shows that the blob wasn’t included in any later blob trees.
