### ISSUE TITLE
How to build a HTTP REST API node

### ISSUE THREAD

**Issue by vae520283995** [onflow/flow-go#2132]
As we all know, for other blockchain projects, access to nodes can be done through jsonrpc or http rest api. The default flow is grpc, but this is a hassle for developers who do not use grpc, although you provide https://rest-mainnet.onflow.org/ and https://rest-testnet.onflow.org/, but for exchanges and wallet providers, it is more convenient to build a node with http rest api by yourself,  can I build a http rest api node by myself? Please provide a tutorial thank you

**Comment by vae520283995** [comment]
@vishalchangrani please help

**Comment by vishalchangrani** [comment]
Hi @vae520283995 - We have already released a REST API. Here is the API docs: https://docs.onflow.org/http-api/ and our [announcement](https://forum.onflow.org/t/flow-everywhere-http-api-on-mainnet/2866).

**Comment by vae520283995** [comment]
> Hi @vae520283995 - We have already released a REST API. Here is the API docs: https://docs.onflow.org/http-api/ and our [announcement](https://forum.onflow.org/t/flow-everywhere-http-api-on-mainnet/2866).
> 

Thank you for your answer, what I want to ask is, can I build a REST API node by myself?

**Comment by vishalchangrani** [comment]
You can implement a converter that exposes a REST API and then calls our gRPC end point. You can also refer to our REST API implementation as a guide. Alternatively, you could run your own access node and implement a custom REST API implementation on top of it.

**Comment by vae520283995** [comment]
> You can implement a converter that exposes a REST API and then calls our gRPC end point. You can also refer to our REST API implementation as a guide. Alternatively, you could run your own access node and implement a custom REST API implementation on top of it.

I see that REST API is already implemented in flow-go
https://github.com/onflow/flow-go/pull/1666
I shouldn't need to implement it myself, but we see the documentation says how to open the REST API port

**Comment by vishalchangrani** [comment]
The REST API end points are mentioned here https://docs.onflow.org/#get-started.
So you can send an HTTP request to these endpoints.
e.g. `curl https://rest-testnet.onflow.org/v1/blocks?height=final` will give you the latest finalized block on testnet.

**Comment by vae520283995** [comment]
> The REST API end points are mentioned here https://docs.onflow.org/#get-started. So you can send an HTTP request to these endpoints. e.g. `curl https://rest-testnet.onflow.org/v1/blocks?height=final` will give you the latest finalized block on testnet.

Are there request rate limits for these two endpoints?

**Comment by vishalchangrani** [comment]
> > The REST API end points are mentioned here https://docs.onflow.org/#get-started. So you can send an HTTP request to these endpoints. e.g. `curl https://rest-testnet.onflow.org/v1/blocks?height=final` will give you the latest finalized block on testnet.
> 
> Are there request rate limits for these two endpoints?

yes - there are rate limits in place. Currently, its 40 request per second per IP for each of the API calls.

**Comment by vae520283995** [comment]
> yes - there are rate limits in place. Currently, its 40 request per second per IP for each of the API calls.

Thank you, I will use the official endpoint first, and I will open an issue if there is a problem later

**Comment by vae520283995** [comment]
@vishalchangrani Hello, after my test, I found that the rate limit is not available for my program, I need to monitor every transaction in the block, when there are too many transactions in the block, the official endpoint cannot be called

**Comment by vishalchangrani** [comment]
> @vishalchangrani Hello, after my test, I need to monitor every transaction in the block, when there are too many transactions in the block, the official endpoint cannot be called

Are you running into rate limits and getting an error code 429 Resource exhausted? I can raise the limits.

**Comment by vae520283995** [comment]
> > @vishalchangrani Hello, after my test, I need to monitor every transaction in the block, when there are too many transactions in the block, the official endpoint cannot be called
> 
> Are you running into rate limits and getting an error code 429 Resource exhausted? I can raise the limits if you want.

Yes, the error code is 429

**Comment by vae520283995** [comment]
> You can implement a converter that exposes a REST API and then calls our gRPC end point. You can also refer to our REST API implementation as a guide. Alternatively, you could run your own access node and implement a custom REST API implementation on top of it.

@vishalchangrani 
Hi, implementing a converter is beyond my capabilities, is there any public project that implements a converter, or can I pay some fee to increase the request rate limit of the REST API, I'm an exchange developer, I think we can go deep cooperate?
