### ISSUE TITLE
Add api to return current version of Protocol/Cadence

### ISSUE THREAD

**Issue by justinbarry** [onflow/flow-go#2134]
## Problem Definition

Projects in the flow ecosystem need a way to handle a backward incompatible change across a spork gracefully.

## Proposed Solution

Add an api of some kind that returns the current spork and the current version of the protocol, version, perhaps other parts of the runtime env.

What are the proposed solutions to this problem?

To make people happy.

## Definition of Done

An api that returns the version numbers of the spork, cadence, access node, etc.

**Comment by smnzhu** [comment]
t’s still unclear to me why we need this as an API?

It should be documented the protocol / cadence version that’s used for each spork, right?

@justinbarry can you explain a bit more?

**Comment by justinbarry** [comment]
@smnzhu Sure but that information needs to be available at runtime. We need to use this information as a feature/behavior flag. 

Let me contrive an example that is pretty nonsensical but illustrates the issue. Assume Cadence team decided for whatever reason during the next spork to reverse the order of arguments passed to a transaction. 

So this:
```
transaction(source: Address, target: Address) {}
```

to have the same behavior post-spork must be written like this:
```
transaction(target: Address, source: Address) {}
```
 
We have two options here when publishing a library other might use:
1. Publish two versions, one for sporkA and one for sporkB. It would be up to us to communicate the need for a version bump at a specific moment in time.
2. Publish one version with both behaviors. This would allow apps to upgrade anytime before the spork and be future compatible.

To handle this gracefully support cases it would need to be able to check at runtime which transaction snippet to send to the chain. The alternative would be to coordinate a

**Comment by bluesign** [comment]
@justinbarry sporks.json doesn't help ? 

https://github.com/onflow/flow/blob/master/sporks.json

**Comment by franklywatson** [comment]
Thanks for the callout here. The metrics you proposed look good, we will investigate if there's anything that can be done with Cadence version
