### ISSUE TITLE
[Testing] Create breaking change detection tests

### ISSUE THREAD

**Issue by smnzhu** [onflow/flow-go#2162]
We want some sort of automated detection of breaking changes to the main models / validation logic for flow.

One option we have is to run these tests as a separate CI job, and name it appropriately so that developers are made aware to notify us if it fails, instead of simply fixing the test. 

Another option is to run it entirely separate from CI, but set things up so we somehow get alerted when it fails.

To start off with, we can focus on creating this test for one of the more common usecases, which is to be able to validate all of the events for a given block.

**Comment by smnzhu** [comment]
https://github.com/tav/flow-accesshash/blob/main/verify-access-api.go

**Comment by smnzhu** [comment]
Let's add this test to this repo: https://github.com/onflow/flow-e2e-tests

**Comment by gomisha** [comment]
https://github.com/tav/flow-accesshash/blob/main/verify-access-api.go is generating 404 error

This link works:

https://github.com/tav/flow-accesshash/blob/fb508e0bb32dac4223dab76f31aa9c009950027b/verify-access-api.go
