### ISSUE TITLE
[MDF] Making go module files siblings instead of interleaved

### ISSUE THREAD

**Issue by szegedim** [onflow/flow-go#2177]
## Problem
There is a go.mod file in the integration directory. Any new enumeration values in the model/flow/role.go will not be propagated to run a successful integration test without changing external github repositories.

## The Proposed Solution
Move integration tests into a different github repository to support changes in `model/flow/role.go`

The change triggering the error:
```
diff --git a/model/flow/role.go b/model/flow/role.go
index f138a185d..384b5128e 100644
--- a/model/flow/role.go
+++ b/model/flow/role.go
@@ -18,7 +18,8 @@ const (
        RoleConsensus    Role = 2
        RoleExecution    Role = 3
        RoleVerification Role = 4
-       RoleAccess       Role = 5
+        RoleFailing      Role = 5
+       RoleAccess       Role = 6
 )

 func (r Role) Valid() bool {
```

An example error:
```
panic: failed to register node: [Error Code: 1101] cadence runtime error Execution failed:
error: pre-condition failed: The role must be 1, 2, 3, 4, or 5
   --> f8d6e0586b0a20c7.FlowIDTableStaking:168:16
    |
168 |                 role >= UInt8(1) && role <= UInt8(5): "The role must be 1, 2, 3, 4, or 5"
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


goroutine 1 [running]:
github.com/onflow/flow-go/fvm.panicOnMetaInvokeErrf(0x1accd03, 0x1b, 0x7fde7d94bd10, 0xc000010a60, 0x0, 0x0)
        /root/stable/work/fvm/bootstrap.go:719 +0x1a5
github.com/onflow/flow-go/fvm.(*BootstrapProcedure).registerNodes(0xc00015c840, 0xc7200a6b58e0d6f8, 0xa62a0ef26b8582ee, 0x792af4e3b63ce50a)
        /root/stable/work/fvm/bootstrap.go:640 +0x13d
github.com/onflow/flow-go/fvm.(*BootstrapProcedure).Run(0xc00015c840, 0xc000f48180, 0x1e13860, 0x2c50090, 0x0, 0x0, 0x1e015d0, 0x2e01f20, 0x0, 0x0, ...)
        /root/stable/work/fvm/bootstrap.go:253 +0x7f5
github.com/onflow/flow-go/fvm.(*VirtualMachine).Run(0xc000f48180, 0x1e13860, 0x2c50090, 0x0, 0x0, 0x1e015d0, 0x2e01f20, 0x0, 0x0, 0x186a0, ...)
        /root/stable/work/fvm/fvm.go:57 +0x2ad
github.com/onflow/flow-go/engine/execution/state/bootstrap.(*Bootstrapper).BootstrapLedger(0xc0005bf2a0, 0x1e0a1f8, 0xc00015a900, 0x0, 0x1e0d048, 0xc0002e11c0, 0x2, 0x1, 0x0, 0x3e8, ...)
        /root/stable/work/engine/execution/state/bootstrap/bootstrap.go:53 +0x43e
github.com/onflow/flow-go/cmd/bootstrap/run.GenerateExecutionState(0xc000156960, 0x19, 0x0, 0x1e0d048, 0xc0002e11c0, 0x2, 0x1, 0x0, 0x3e8, 0x0, ...)
        /root/stable/work/cmd/bootstrap/run/execution_state.go:54 +0x555
github.com/onflow/flow-go/integration/testnet.BootstrapNetwork(0xc0000f8680, 0xb, 0x10, 0x0, 0x0, 0x0, 0x198f813, 0x8, 0x1, 0x7d0, ...)
        /root/stable/work/integration/testnet/network.go:1131 +0x1865
main.main()
        /root/stable/work/integration/localnet/bootstrap.go:154 +0xaae
exit status 2
make: *** [Makefile:20: init] Error 1
```

---

### Note

This is part of the decision framework described in https://github.com/dapperlabs/bamboo/issues/576 . 
These issues are meant to be resolved quickly, therefore:
- Comments or discussions should happen in direct communication (slack, sync, etc')
- Comments on this thread should be limited to one of these short replies:
  - `I agree`
  - `I'm OK with this`
  - `I would like further discussions before deciding`
  - `I disagree`

**Comment by szegedim** [comment]
This is an example of such dependencies:
```
https://github.com/onflow/flow-core-contracts/blob/26afc84a19039ae7e6628b4bc4b4f53083be4abc/contracts/FlowIDTableStaking.cdc#L168
```

**Comment by szegedim** [comment]
Please refer to the following doc to justify the change: https://go.dev/ref/mod

- A **module** is a collection of packages that are released, versioned, and distributed **together**.
- A module is identified by a **module path**, which is declared in a **go.mod** file.
- Each **package** within a module is a collection of source files in the same directory that are **compiled together**.
- A **package path** is the module path joined with the **subdirectory** containing the package relative to the module root.
- The **module root** directory is the directory that **contains the go.mod** file.
- The **main module** is the module containing the directory where the **go command is invoked**.
- A **module path** is the canonical name for a module, **declared in the module’s go.mod file** with the module directive. 
- Typically, a **module path** consists of a repository **root** path, a **directory** within the repository (usually empty), and a major version suffix (only for major version 2 or higher).

Discussion: This means that a repository can only have one **root direcotry** with go.mod.

Proof: Should it have multiple root directories under the same path, we would identify a package with two package paths, one is a substring of another. Two modules should have different module paths as identif	iers and different dependencies in separate go.mod files. We may build both by running Go from the path of the two `go.mod` files separately as the main module of the build. The specification at https://go.dev/ref/mod will resolve github.com/onflow/flow-go/integration **in parallel**.
- Request for the latest version of go.mod in github.com/onflow/flow-go/integration
- Request for the latest version of go.mod in github.com/onflow/flow-go/
- Request for the latest version of go.mod in github.com/onflow
It will find both `go.mod` files in `flow-go` and `flow-go/integration` **in parallel**. The choice of module chosen will be **indeterministic** based on the official specification above.

**Comment by franklywatson** [comment]
Not moving ahead due to other priorities
