### ISSUE TITLE
Service for indexing Accounts and Keys

### ISSUE THREAD

**Issue by pgebheim** [onflow/flow-go#2179]
## Problem Definition

Currently, there is no standard API or service for indexed Flow Accounts along with their corresponding account keys for quick lookup. This means that all wallets or services which need this mapping are forced to solve this problem themselves, which is tricky / heavy for historical data.

## Proposed Solution

- Create a service which iterates through all accounts (https://github.com/onflow/cadence/pull/1434) and tracks their keys
- This service should run occassionally, updating checking for new accounts, and grabbing events for account changes.
- Write service in such a way that it will be able to use the new execution state tracking API from the Access Node Refactor project. Once that is available this service can be integrated as an extension of the access node.
- Service should have simple gRPC/REST API
   - Notes: Probably need paging?
   - getAccountKeys(key, keyIndex, [weight?], [isRevoked?])
   - getKeyAccounts(account, signingAlgo, hashingAlgo)
     - HEX representation of public key
     - key, [[crypto algo], hashing algo]
- Response Payload:
  - Full response of account? Just key?
  - Suggestion: index, weight, algo stuff 

## Conversation on potential issues
- initial bootstrapping will be request heavy
  - Need to batch accounts to get the data (1k-2k at a time)
  - Using 10 concurrent clients gets done in 10 minutes

- polling every X blocks / seconds for new events
  - Probably not super heavy on the execution node
  - once access node re-arch is done it will hit Access Layer (DPS etc)
  - don't need to implement the follower
 
- sporks
  - Write the client such that if it gets "Unavailable" and then backs off

- Any verification?
  - No?

- explore and tune the bootstrapping parameters before opening it up
- maybe have it spit out a bootstrap DB?

## Definition of Done

TBD

**Comment by peterargue** [comment]
@bthaile I think you created something like this already right? is this still needed?

**Comment by bthaile** [comment]
Yes, the service is hosted https://key-indexer.production.flow.com/status

My version was meant to be an example. I think there are better ways to do it now.
Here is the repo. 
https://github.com/onflow/flow-public-key-indexer
