### ISSUE TITLE
[Execution State] In MTrie, payload.Equals() shouldn't compare payload's key

### ISSUE THREAD

**Issue by fxamacker** [onflow/flow-go#2198]
## Problem

In MTrie, payload key shouldn't be included in payload equality test.

Also, the expectation that MTrie expects payload's key to never change doesn't appear to be documented.

Thanks @AlexHentschel for pointing out payload key is auxiliary data and for suggesting we add a comments.  👍 

## Solution

- Modify `payload.Equals()` so it doesn't compare payload's key.
- Add a comments to API to indicate MTrie expects payload's key to never change.

Although payload key was compared in `payload.Equals()` for about a year, this is an edge case that isn't triggered by our current use of MTrie.  So this change isn't expected to cause compatibility issues.

**Comment by ramtinms** [comment]
I think Equal is mostly used for testing, I don't think the functional aspect of the protocol uses those functionalities

**Comment by fxamacker** [comment]
@ramtinms Yeah, we're primarily concerned about its use in `update`:

https://github.com/onflow/flow-go/blob/2893f140e3570f5b6442be9bb22804a20347c636/ledger/complete/mtrie/trie/trie.go#L365
