### ISSUE TITLE
[Access Node] Refactor Access API into Protocol API

### ISSUE THREAD

**Issue by AliSMAmin** [onflow/flow-go#2318]
## Problem Definition

Currently, an Access Node is essentially a collection of five engines. One of them is the RPC Engine, or "Access API." It is a GRPC server which responds requests from clients and supports GRPC Web Proxy requests. Its specifications are defined with protocol buffers. This issue is a part of staging the Flow Blockchain Data Service. The entry-layer consists of various data serving components, including the Protocol API. The Access API allows Access Nodes/Observer to send RPC calls and query the blockchain directly. On the Access Node, both read/write requests are forwarded directly to Collection/Execution Nodes. On an Observer, all Access API requests are first proxied through an Access Node.

This issue suggests that the Access Node and Observer Service's exposed gRPC engine (Access API) undergo a few changes. The Access API should have its functionality divvied into two new APIs: the Protocol API and Execution State API. These two APIs should interface with external clients, such as DPS (Data Provisioning Service). Ultimately, only write requests should eventually forwarded over staked libp2p into the network.

The effort tracked here is specifically for the preliminary steps pertaining to building the Protocol API out of the Access API. A separate issue will track the effort pertaining to the Execution State API.

## Proposed Solution

Begin refactoring the Access API into two separate APIs. Firstly, Refactor the Access API/gRPC engine in the Access Node and Observer for Protocol State access without travelling to a Collection or Execution Node for each request. Flow Core Blockchain Service operators have read/write calls sent to the correct destinations, so that they can update the chain and read state data without compromising architectural integrity.

## Step Definitions:

- Update Access API to read and write to Protocol DB
- Alter Access API to forward read queries to the Protocol DB instead of Collection/Execution
- Ensure Access Nodes are still able to send write APIs to Collection/Execution
- Ensure Observers are still able to proxy write APIs to Access Nodes

## Definition of Done

The Protocol API is built out with all requisite components and placed in both the Access Node/Observer service with correct references. The Protocol API provides access to the blockchain's synchronized state.

If an Access Node submits a write query, the Protocol API forwards that over the staked libp2p network to Collection or Execution Nodes.

If an Access Node submits a read query, the Protocol API forwards that to the Protocol DB. It returns the resulting block to the client.

If an Observer service submits a write query then the Protocol API forwards it over unstaked libp2p to the configured Access Node. The configured Access Node will then forward it over the staked network to Collection or Execution.

If an Observer Service submits a read query, then Protocol API forwards that to the Protocol DB. Block information which is not persisted in the Protocol DB must be requested over unstaked libp2p from an Access Node, then persisted in the Protocol DB for subsequent requests.

**Comment by peterargue** [comment]
Thanks for the writeup @AliSMAmin!

I'm thinking for backwards compatibility while this is built out, we should build it as a new service, which will eventually replace the current access API (combined with the flow api service).

The Protocol API should be a gRPC API which provides readonly access to the protocol state that exists on the node/observer. The endpoints will be a subset of the endpoints in the existing Access API, along with `SendTransaction` which is only supported on Access Nodes. For now, observers can return `UNIMPLEMENTED` for `SendTransaction`.

Besides `SendTransaction` there shouldn't be any write requests, and there shouldn't be any interactions with libp2p. The Protocol API should just expose data within the existing protocol db, much like what the access api does today.

**Comment by AliSMAmin** [comment]
This is helpful @peterargue. We will go ahead and implement it as a new service instead of altering the Access API so that it can be phased in without affecting current functionality.  I have also noted that the Protocol API doesn't need any libp2p exposure.

**Comment by AliSMAmin** [comment]
This issue covers the effort pertaining to the Execution Data API: https://github.com/onflow/flow-go/issues/2384

**Comment by AliSMAmin** [comment]
Behavior Driven Design Spec:

`Title:` Update Access API to read and write to ProtocolDB
`Feature:` The Access API reads and writes updates to a cache in addition to communicating with Flow.
`Narrative:` 

`As a:` Access Node or Observer Operator
`I want:` the Access API to read and write to the Protocol DB
`So that:` I can receive data from Flow and then store blockchain data locally to be read

`Rule:` Write requests are ultimately sent to a Collection or Execution Node
`Notes:` this is a part of the overall Access API refactoring into Protocol API

`Background: `Johnny would like to use his Access Node to query Flow’s first few transactions

`Given:` Build-out of the ProtocolDB & State streaming modules
`When:` an Access Node or Observer Service has initialized
`Then:` it persists data in ProtocolDB from the beginning of the spork

`And When:` Johnny sends an API call for blockchain data
`Then:` the Protocol/Access API reads it from the ProtocolDB and returns it to the client

`But:` if the data is not available
`Then:` ProtocolAPI returns error to Flow API sevice

`And When:` Client sends a write API call
`Then:` it is persisted in ProtocolDB in addition to being sent to Flow

**Comment by AliSMAmin** [comment]
PR for this is at https://github.com/onflow/flow-go/pull/2370

**Comment by franklywatson** [comment]
Duplicates https://github.com/onflow/flow-go/issues/2420
