### ISSUE TITLE
GetEventsForHeightRange should never return hash of unknown transaction

### ISSUE THREAD

**Issue by ninkibah** [onflow/flow-go#2341]
My code uses the C++ gRPC interface and all functions mentioned below refer to calls using this protocol.

In crawling the current **testnet** chain just now, somehow I was told that the transaction `230ebf10abb9d6cbd765ca7bb081b5889a933bcb9f480868183a85571b506318` couldn't be found, and yet this hash was one of the ones I got back from GetEventsForHeightRange.
```
[E] FlowCommunication::getTransactionByHash - 5: no known transaction with ID  30ebf10abb9d6cbd765ca7bb081b5889a933bcb9f480868183a85571b506318
[W] FlowCommunication::getEventsByInterval: Couldn't read txnHash 230ebf10abb9d6cbd765ca7bb081b5889a933bcb9f480868183a85571b506318 in block range: 66641493 - 66641502
```

My belief is that `GetEventsForHeightRange` should never return transaction hashes which can't be found.

The `GetEventsForHeightRange` call used either the `A.7e60df042a9c0868.FlowToken.TokensWithdrawn` or `A.7e60df042a9c0868.FlowToken.TokensDeposited` event with a height range of 66641493 - 66641502.

I have seen examples of this happening on both mainnet and testnet. I expect to see it maybe once or twice per day.

**Comment by m4ksio** [comment]
Hi,
`230ebf10abb9d6cbd765ca7bb081b5889a933bcb9f480868183a85571b506318 ` is a service transaction for testnet.  (`b4fc3d14db4df4040e530f63d9debbecab0a587e20a039320e286d42261522e5` for mainnet)
You see it rarely because this transaction produces events rarely, but its part of every block

**Comment by ninkibah** [comment]
Is this why I can't ask `GetTransaction` and  `GetTransactionStatus` for it?

Can I code my crawler to ignore these transaction hashes, safe in the knowledge that I won't miss any of our client's deposits or withdrawals?

**Comment by ninkibah** [comment]
Maks, thanks for those tips. The two new calls should drastically reduce the number of calls I make to the chain.
