### ISSUE TITLE
Migrate subset of Access Node API to Protocol API

### ISSUE THREAD

**Issue by koko1123** [onflow/flow-go#2420]
Migrate the following Access Node APIs to the Protocol API created. All the following APIs should not require execution state sync to serve their data lookups:

`GetLatestBlockHeader`
`GetBlockHeaderByHeight`
`GetBlockHeaderByID`
`GetLatestBlock`
`GetBlockByHeight`
`GetBlockByID`
`GetExecutionResultForBlockID`
`GetExecutionResultByID`

**Comment by koko1123** [comment]
@alavallee21 should have this in his [PR](https://github.com/GetElastech/flow-go/pull/10/files)

**Comment by koko1123** [comment]
duplicated by #2138

**Comment by AliSMAmin** [comment]
https://github.com/onflow/flow-go/pull/2701

**Comment by koko1123** [comment]
outdated issue; closing
