### ISSUE TITLE
Add Support to Streaming Client Library for Syncing Execution State

### ISSUE THREAD

**Issue by AliSMAmin** [onflow/flow-go#2466]
**Problem Definition**

This Epic is concerned with the Streaming Client Library, a part of the [Flow Access Node Refactoring](https://forum.onflow.org/t/flow-access-architecture-specification/2902).

The Streaming Client Library determines how services, such as DPS, remain in sync with upstream protocol and execution state data. This library consolidates logic in one place for both Protocol state and Execution state data.

The Execution Data API’s streaming endpoints as per [#2421](https://github.com/onflow/flow-go/issues/2421) are meant to be consumed by this Streaming Client Library.

This interface allows open-source collaborators to expand Blockchain Data Service functionality.

**Step Definitions**

● Configurable with an Access Node/Observer address when DPS or other service is initialized
● Sync with upstream execution state coming from execution data module
● Feeds data to DPS consensus and execution trackers
● Pub/sub from streamer consumers
● Consumer is configured with an Access Node/Observer address when first initialized

**Definition of Done**

● Client library registers itself as a new execution data consumer to the Execution Data API
● Upon registration with Execution Data API, streams sealed block data from the beginning of the spork
● Can obtain new execution data
● Deliver data in order of finalization (seal)
● New DPS client library can interface with abstracted Consensus follower library

**Comment by koko1123** [comment]
Reduntant issue: https://github.com/onflow/flow-archive/issues/32
