### ISSUE TITLE
Build-Out Flow API on Flow API Service

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-go#2485]
@AliSMAmin commented on [Mon May 16 2022](https://github.com/onflow/flow/issues/942)

**Context**

Related to issue [#940](https://github.com/onflow/flow/issues/940). This epic pertains to the Flow API Service, a part of the wider [Flow Access Node Refactoring](https://forum.onflow.org/t/flow-access-architecture-specification/2902).

**Proposed Solution**

The Flow API Service will become its own standalone service hosting the Flow API, renamed from Access API. 

**REMOVED DUE to COMPLEXITY CONCERNS cf.** https://github.com/onflow/flow/issues/943

_Internally the Envoy proxy will handle routing to the appropriate component, Blockchain Data Service or DPS, depending on whether a script or a transaction._

**Step Definitions**

•	Flow API Service serves the Flow API
•	Expose the external Flow APIs (gRPC/REST)
•	Flow API responds to requests

**Definition of Done**

•	Flow API successfully queries the downstream Protocol API for protocol state
•	Successfully sends transaction requests from clients to the Protocol API on an Access Node or Observer Service
•	Endpoints are exposed that query the protocol state & forward requests to the downstream Protocol API

**Comment by szegedim** [comment]
Here is the passing test for this change on the Access APi: https://github.com/GetElastech/api-service/actions/runs/2776003280
@A-town21 is adding the protocol changes. We might have some design suggestions soon.

**Comment by koko1123** [comment]
redundant issue
