### ISSUE TITLE
HTTP API - POST /v1/scripts does not return JSON response

### ISSUE THREAD

**Issue by rmberg** [onflow/flow-go#2601]
## 🐞 Bug Report

The response when calling the HTTP API execute script endpoint (`POST /v1/scripts`) does not return a JSON encoded response. It simply returns the base64 encoded string response of the script execution.

It seems like on this line: https://github.com/onflow/flow-go/blob/master/engine/access/rest/scripts.go#L35 the backend response is being returned without first being wrapped in an `InlineResponse200`.

## What is the severity of this bug?

**Should have:** * It would be better if we do this before we ship, but it's OK if we don't (product functions without this, but it's a better user experience). Consider adding to a future sprint.

## Reproduction steps

Steps to reproduce the behaviour:

1. Execute this curl command:
```
curl --request POST \
  --url https://rest-testnet.onflow.org/v1/scripts \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --data '{
	"script": "cHViIGZ1biBtYWluKCk6IFN0cmluZyB7CiAgICByZXR1cm4gIkhlbGxvIFdvcmxkIgp9",
	"arguments":[]
}'
```

Observe the response:
```
"eyJ0eXBlIjoiU3RyaW5nIiwidmFsdWUiOiJIZWxsbyBXb3JsZCJ9Cg=="
```

- [ ] I followed these steps and was able to reproduce the issue

## Expected behaviour

The expected response is:
```json
{
  "value": "eyJ0eXBlIjoiU3RyaW5nIiwidmFsdWUiOiJIZWxsbyBXb3JsZCJ9Cg=="
}
```

## Specifications

- System: (e.g. macOS 10.13.4, Linux)
- Go: (e.g. 1.13)

**Comment by franklywatson** [comment]
We will address this in a future version of the API
