### ISSUE TITLE
Add handlers to State sync / Execution Data sync to stream to consumers

### ISSUE THREAD

**Issue by koko1123** [onflow/flow-go#2687]
Register new handlers with `OnBlockFinalized` (in execution data sync) and `OnFinalizedBlock` (in state sync) in the observer engine to `stream.send` the data received to all consumers in their respective `live` consumer caches

**Comment by szegedim** [comment]
Optional: Was a common name of the same data/event e.g. OnBlockFinalizationEvent considered?

**Comment by peterargue** [comment]
this was implemented here: https://github.com/onflow/flow-go/pull/3723
