### ISSUE TITLE
State Sync: port execution ID verification to current requester engine

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-go#2715]
The execution data ID verification PR: https://github.com/onflow/flow-go/pull/2647

This is currently based against the optimistic requester: https://github.com/onflow/flow-go/pull/2292

We need to merge the latter (or at least the parts of it that the former depends on) so that the former can be merged.

**Comment by peterargue** [comment]
This was addressed by https://github.com/onflow/flow-go/pull/4586
