### ISSUE TITLE
[HTTP API] Add the `getNetworkParameters` endpoint

### ISSUE THREAD

**Issue by srinjoyc** [onflow/flow-go#2755]
## Problem Definition
Not having a chain-id return from an AN is causing a lot of issues for their wallet not being able to identify which network it should be signing for without hardcoding url mappings (which is not very viable with AN's such as Alchemy changing their URLs). Especially prominent for wallets like Lilico offering a 'dev mode'. They are currently blocked by this.

## Proposed Solution
Add the `getNetworkParameters` [endpoint](https://docs.onflow.org/access-api/#network-parameters) from the GRPC API to the REST API.  Wallets that have a 'developer mode' which could work on any network are having issues.

**Comment by lmcmz** [comment]
Is there any update on this 😿 ?
More and more dev running into this issue on our end.
And the new wallet connect method will be affected as well.

**Comment by vishalchangrani** [comment]
Is the ask here to provide the gRPC [getNetworkParameters](https://developers.flow.com/nodes/access-api#getnetworkparameters) call on the REST API?

**Comment by JeffreyDoyle** [comment]
@vishalchangrani , that would be ideal, to have both REST and GRPC APIs support [getNetworkParameters](https://developers.flow.com/nodes/access-api#getnetworkparameters) call. This would unblock FCL in completing this issue: https://github.com/onflow/fcl-js/issues/304.
