### ISSUE TITLE
Fix Epoch Join Leave VN

### ISSUE THREAD

**Issue by DEPRICATED-Dapperlabs-ex-employee** [onflow/flow-go#2776]
## Problem Definition

The test TestEpochJoinAndLeaveVN is currently failing in CI. Fix this test.

## Proposed Solution

Update the test and or infrastructure to resolve test issues. 

## Definition of Done

Test is no longer failing as part of CI on all cases.

**Comment by AndrewM-SDET** [comment]
Waiting for @jordanschalm to return from OOO.

**Comment by jordanschalm** [comment]
The test is [enabled on CI](https://github.com/onflow/flow-go/blob/058e3c4e76f292c060957b7a6111fa2a25f3dc57/integration/tests/epochs/cohort2/epoch_join_and_leave_vn_test.go#L34-L38) - I think this is just outdated.
