### ISSUE TITLE
[State Sync] Improve ExecutionDataRequester stability when peers become unavailable

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-go#2797]
## Problem Definition

The `ExecutionDataRequester` uses [bitswap](https://docs.ipfs.io/concepts/bitswap/) to download execution data from Execution nodes and other Access nodes. This is live on testnet and mainnet. However, there have been some issues when peers leave the network (e.g. reboots, networking issues, etc) where all nodes suddenly are no longer able to find certain execution data blobs. After restarting, the nodes will always catch up. Typically, only one AN needs to be restarted, then all the others become unstuck.

Talking with the bitswap devs, this is most likely because the bitswap client only detects peers that connect after the bitswap network was started on the node. So any nodes that connected before are never added creating a fragmented network.

## Proposed Solution

Update the bootstrapping logic to start the bitswap network before connecting to peers.

## Definition of Done

Bitswap is started before the node connects to any peers, allowing it to have a full view of the network.

**Comment by franklywatson** [comment]
Duplicates: https://github.com/onflow/flow-go/issues/2718
