### ISSUE TITLE
Loader - Clean Runs

### ISSUE THREAD

**Issue by DEPRICATED-Dapperlabs-ex-employee** [onflow/flow-go#2871]
## Problem Definition

The loader tests are very trusting, they do no verification on failed transactions or other errors. We need to track and report these rather than simply assuming that these failures are "normal"

## Proposed Solution

Validate that during a run there are no errors or pseudo errors (transaction execution errors).
If a test run has errors report them to the test runner and log them in BigQuery (if part of a CI run)

## Definition of Done

Add unit tests that force failures and make sure they are properly reported
Verify that we are able to run a clean test and that when we do we note it in final results.

**Comment by AndrewM-SDET** [comment]
Work for this ticket can be found on branch https://github.com/onflow/flow-go/tree/2871-ErrorTracking a PR will be opened in the next few days in draft-mode once I have the basic functionality fleshed out.
