### ISSUE TITLE
[Observer] Improve upstream gRPC failovers with AN connection pooling

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-go#2955]
## Problem Definition

The observer's gRPC interface has functionality to forward gRPC requests that it cannot server locally to an upstream AN. The code is here: https://github.com/onflow/flow-go/blob/4b6dd69e732991087ba70287f4b6f99dba72cdff/engine/access/apiproxy/access_api_proxy.go

There's a section where it handles reconnecting to the upstream when there's a connection error here:
https://github.com/onflow/flow-go/blob/4b6dd69e732991087ba70287f4b6f99dba72cdff/engine/access/apiproxy/access_api_proxy.go#L50-L128

We discovered while building the AN connection pooling feature that the methods used for detecting issues with the connection are unreliable and likely to cause unnecessary errors.

## Proposed Solution

Rather than maintaining to implementations of connection pooling, use the AN's connection pool here.

**Comment by SaveTheRbtz** [comment]
A side note, we can always consider borrowing the connection pooling from a mature API, like google's: https://pkg.go.dev/google.golang.org/api/transport/grpc
