### ISSUE TITLE
[FVM] Populate Programs Cache from scripts

### ISSUE THREAD

**Issue by janezpodhostnik** [onflow/flow-go#2975]
## Problem Definition

The programs cache contains elaborations of smart contracts.

If the programs cache is reset because:
- node restated
- contract deployed
- contract upgraded

Programs cache is currently only populated for the contracts imported by **transactions** .

Some scripts are importing a lot of heavy contracts. Cache misses in this case might cause the scripts to go over the 10s time limit. This was the case for Alchemy scripts recently. This is not so much of a problem for transactions, as if you keep sending the same transaction over and over the cache will be filled with the first one.

## Proposed Solution

Also cache contracts from scripts.

Extra: log cache misses

## Definition of Done

- calling the same script twice for the same block should only cause a cache miss the first time

**Comment by j1010001** [comment]
Not needed once script execution moves to Archive node
