### ISSUE TITLE
Create and deploy contract for synchronising versions

### ISSUE THREAD

**Issue by m4ksio** [onflow/flow-go#3046]
In order to synchronise EN version switchover, as described in a [design document](https://www.notion.so/dapperlabs/Execution-Nodes-rolling-updates-4a3984b868c24e3fb00e1c0d40857d8e?d=02e6681621724dd3a543ad9b1568a680#98da50ac701346e6b105f85ca5f95767) height to version map is to be stored as part of service account, and thus available to every node in an uniform manner.

It should be designed with https://app.zenhub.com/workspace/o/onflow/flow-go/issues/3047 

This includes first actually defining and designing the best approach to the problem, and then implementing it.

**Comment by j1010001** [comment]
duplicating: https://app.zenhub.com/workspaces/flow-protocol-execution--verification-team-61b0f8323e24eb00135c73e3/issues/onflow/flow-go/2734
