### ISSUE TITLE
Add a `--fast` mode to checkpoint-list-tries cmd

### ISSUE THREAD

**Issue by zhangchiqing** [onflow/flow-go#3189]
## Context

The checkpoint-list-tries cmd is able to output all the tries root hash included in a given checkpoint file. 

However, it takes a long time to print for mainnet checkpoint file, because it has to the entire checkpoint file to memory and then print each trie by calculating the root hash. The checkpoint file reading takes about 6 mins.

Since the number of tries and their root hashes are already written to the end of the file, it's possible to just read the tries by read parts of the checkpoint file. We just need to calculate the position of the file to read from.

This could speed up getting the tries from a checkpoint file, which is useful when rolling back execution to a certain height.

**Comment by Tobenna-KA** [comment]
Hi @zhangchiqing care to elaborate more on this? If it hasn't been done in some other branch, I would like to take a look at it

**Comment by zhangchiqing** [comment]
Hi @Tobenna-KA , thanks for looking into this issue. It hasn't been done yet. 

This issue is to add a `--fast` flag to [the checkpoint-list-tries cmd ](https://github.com/onflow/flow-go/blob/master/cmd/util/cmd/checkpoint-list-tries/cmd.go) , so that instead of [loading the checkpoint file](https://github.com/onflow/flow-go/blob/master/cmd/util/cmd/checkpoint-list-tries/cmd.go#L32), which takes a long time if the checkpoint is big, it can just read the trie root hashes from the checkpoint file. 

In checkpoint V6, the trie root hashes [are saved in the last checkpoint part file](https://github.com/onflow/flow-go/blob/master/ledger/complete/wal/checkpoint_v6_writer.go#L255), so we just need to read it from that file.

Note, we can't reuse [the code from the V6 checkpoint reader](https://github.com/onflow/flow-go/blob/master/ledger/complete/wal/checkpoint_v6_reader.go#L597) to read it, because the checkpoint reader after reading the root hash does extra work, such as finding the root node's child nodes, and create the root node. 

We just need to find the file position for the trie root hashes, and read the bytes and print them in the cmd.

## why adding a flag?
Since the `--fast` mode will just read the trie root hashes from checkpoint file, it does not validate the trie root hash, whereas running the cmd without the `--fast` flag will load the checkpoint first, go through all the validation, and only return the trie hashes after passing the validation, however it will also be slower.

**Comment by zhangchiqing** [comment]
This PR added a `ReadTriesRootHash` function to read all the trie root hashes from a checkpoint file, so that the `--fast` mode could simply use that function to list all the trie root hashes.
