### ISSUE TITLE
Version hell and semver

### ISSUE THREAD

**Issue by bluesign** [onflow/flow-go#3217]
## Problem Definition

Is there any chance you can adapt semver across all repos and split some stuff? Again everything I am working on broke, had to debug few hours yesterday. I don't know if any soul ( non dapper employee ) other than me trying to develop something using fvm, cadence, emulator etc. But it is living hell on earth. 

I know you guys are moving fast, and I am totally happy with that. But there is not a single trace of what is happening, what is breaking, what can break. 

I am trying to keep up with all, I am almost subscribed to all repos on onflow, but I am still missing stuff. I see you all also not happy with this,  isn't there a solution ? Trying to develop anything on flow ecosystem, other than contracts, practically not possible.

**Comment by bluesign** [comment]
Some example: 

Emulator uses: 
https://github.com/onflow/flow-emulator/blob/f96b66e8846d1ec57bc8373f9e42db221063eb64/go.mod#L16-L17

Lastest flow-go release (0.27.4) uses: 
https://github.com/onflow/flow-go/blob/b6e9a988514d13e1e1ecd0802d7e02f9e9b1415b/go.mod#L61

**Comment by bjartek** [comment]
This is still causing issue to this day. Please adapt this.
