### ISSUE TITLE
Add "total unweighted execution effort per block" metric to EN

### ISSUE THREAD

**Issue by Tonix517** [onflow/flow-go#3312]
## Problem Definition

We want to add a new performance metric to EN, so that we can track the effect of EN code optimizations over time. 
At present, we only have transaction execution time, which depends on transaction content itself and is not ideal as a measure of EN performance - the Txs executed are outside of our control. The execution metrics that exists today is also per Tx, which is a lot of data that takes a lot of time to process in grafana.

## Proposed Solution

We can create a new performance metric of total unweighted Execution Effort per block to better measure EN performance. The advantage of having so is that it is network load independent. That is, no matter how other factors (network etc.) change, for the same tx we will have the same measurement. Thus, we will have such a measurement that can relatively, if not perfectly, reflect what a transaction actually does: state read/write, creating an account and cadence invocations/lines/loops.

**NOTE** at present the Execution Effort values have weight applied. Since this weight may be re-adjusted, and it is pretty much customer facing concept, we'd better off to use an un-weighted Execution Effort for performance measuring purposes so that it can stay weights-change free.

## Definition of Done

A new "total unweighted Execution Effort per block" metric is emitted from EN.

## Remaining
- [ ] Create Grafana Dashboard

**Comment by j1010001** [comment]
Chatted to @vishalchangrani, he did some work with Marcelo to define recording rules in prometheus (https://github.com/dapperlabs/SRE/blob/master/services/prometheus/recording-rules/prometheus/flow-slos.yaml) - we could do something similar here - we could emit per-tx event (maybe add it to the existing log as unweighted event) and then add a recording rule to aggregate this per-Tx metric per block, that way the EN needs to do less work potentially.

**Comment by janezpodhostnik** [comment]
this would also be valuable source of information for execution effort calibration. We just need to make sure that execution time is also available (which I think it already is)
