### ISSUE TITLE
Release flow-go more frequently

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/flow-go#3360]
## Problem Definition

Currently repositories using flow-go (for example, flow-emulator) are required to use commit hashes in order to obtain newer fixes and features. There is no good reason for this, and it makes it difficult to track what's going on with dependencies. Furthermore, the release notes are ridiculously long when a release is finally done, which makes catching up on and finding changes more difficult. Please release flow-go updates more incrementally.

**Comment by bluesign** [comment]
I raised this before: https://github.com/onflow/flow-go/issues/3217

Ofc like many of the important issues it is ignored.
