### ISSUE TITLE
[Active Pacemaker] Misc improvements

### ISSUE THREAD

**Issue by AlexHentschel** [onflow/flow-go#3439]
This issue holds a list of misc suggestions for improvements and revisions.

## High priority 
- [x] Consensus Follower queueing inbound blocks:
   * At the moment, the [consensus follower has only an unbuffered channel for inbound blocks](https://github.com/onflow/flow-go/blob/62b57dcdea46f005f21b2ed37737df347c89db98/consensus/hotstuff/follower_loop.go#L30), which will potentially block the follower's compliance engine. I think we should use a _buffered_ channel for inbound blocks, similarly to the [consensus participant](https://github.com/onflow/flow-go/blob/62b57dcdea46f005f21b2ed37737df347c89db98/consensus/hotstuff/eventloop/event_loop.go#L41-L47)
   * furthermore, the follower currently can [block compliance go-routines](https://github.com/onflow/flow-go/blob/62b57dcdea46f005f21b2ed37737df347c89db98/consensus/hotstuff/follower_loop.go#L44), which could prevent a graceful shutdown. I think we should add logic similar to the [consensus participant](https://github.com/onflow/flow-go/blob/62b57dcdea46f005f21b2ed37737df347c89db98/consensus/hotstuff/eventloop/event_loop.go#L261-L265)
- [ ]  ...

## Medium priority 
- [x] At the moment, the `hotstuff.Consumer` emits the following event when it produced a block proposal that can be published: 
https://github.com/onflow/flow-go/blob/c20f2cf79c8b1707db9900c57b09ec1a40c132cf/consensus/hotstuff/consumer.go#L260
    The `delay` here specifies some sleep time before the proposal is broadcast to other nodes. Though, `delay` is ambiguous, because it is always in _reference to some point in time_ `t`, which we don't specify. From the component publishing this notification ([`EventHandler`](https://github.com/onflow/flow-go/blob/c20f2cf79c8b1707db9900c57b09ec1a40c132cf/consensus/hotstuff/eventhandler/event_handler.go#L449)), `t` is the point in time when the event is published. However, in our asynchronous, event-driven design, there could be quite a large uncertainty as to when the source emitted the notification. 

   I think this problem could be resolved with little effort:
   * instead of a `delay` we could be using the `targetPublicationTime`. 
   *  We could need to change the calculation in the EventHandler: https://github.com/onflow/flow-go/blob/c20f2cf79c8b1707db9900c57b09ec1a40c132cf/consensus/hotstuff/eventhandler/event_handler.go#L439-L449 and replace it by
      ```golang
      // raise a notification with proposal (also triggers broadcast)
      header := model.ProposalToFlow(proposal)
      targetPublicationTime := start.Add(e.paceMaker.BlockRateDelay())
      e.notifier.OnOwnProposal(header, targetPublicationTime)
      ``` 
   * and update the corresponding logic in the `MessageHub` (collector and consensus) accordingly
- [ ] ...

## Low priority 
- [ ] ...

**Comment by durkmurder** [comment]
The one related to `targetPublicationTime` has been already completed and merged into `feature/active-pacemaker` in scope of https://github.com/onflow/flow-go/pull/3357
