### ISSUE TITLE
Index service events by block height

### ISSUE THREAD

**Issue by m4ksio** [onflow/flow-go#3535]
For further development of rolling upgrade mechnism we need an ability to quickly find the nearest VersionUpdate service event.
As the mechanism is intended to work on all node types, we want to consensus follower to create an index allowing to iterate service events by finalized height.

**Comment by m4ksio** [comment]
For further development of rolling upgrade mechnism we need an ability to quickly find the nearest VersionUpdate service event.
As the mechanism is intended to work on all node types, we want to consensus follower to create an index allowing to iterate service events by finalized height.

**Comment by zhangchiqing** [comment]
Reading @jordanschalm 's [comment ](https://github.com/onflow/flow-go/pull/3605#discussion_r1030615979) on the PR, makes me to think about this question:

If block 100 includes a transaction which will produce a result that is included in block 102, and the result will emit a VersionUpdate service event saying from block 200, the Version will be changed from v1 to v2, then how would like to query the data?

I think we would like to have a `VersionByHeight(height)` function which returns:
- v1 if height < 200
- v2 if height >= 200

right?

In that case, we might want to add index as the following key-value pairs:
```
ServiceEvent_VersionUpdate_1: v1
ServiceEvent_VersionUpdate_200: v2
```

So the `200` is not the height that includes the result, but the height that the version will change, right?

**Comment by m4ksio** [comment]
Good question. 
I wanted to made changes in stages, for one thing to keep the PR shorts.
There are three things at play here:
- Version change must only come from sealed blocks (we can't handle situation when, for example, we have a fork which produces two different version change)
- For this to be useful we will prevent version change within X blocks, probably 1000 - so there is space for service event to be sealed before it takes effect (I was told we made similar assumption in few places already, that the gap before sealing/fork length won't be overly long)
- Version change doesn't have to be linear - I think this directly answers why we want to keep service event index instead. One event can produce a table, lets assume
1000 v1
2000 v2
and another later one
1500 v1
2000 v2
While of course we could capture this in an index, it seems like much more work (finding obsolete entries).

Secondly, we need to be able to see versions on different chain height. Ie. EN should stop based on executed height (imagine if execution is behind finalization), while for example LN might want to react to finalized height.
