### ISSUE TITLE
Exposing spork ID as a Prometheus Metric

### ISSUE THREAD

**Issue by vishalchangrani** [onflow/flow-go#3597]
## Problem Definition

What problem is this solving?

The Metrika node agent needs to identify which spork the node software is currently running on. If the node software is not on the current spork, then Metrika analytics can raise an alert and also stop reporting the node metrics.
However, the metrika node agent does not have access to the genesis data used by the node software. It can only query the Prometheus metrics and the node logs.

To allow for the Metrika node agent to detect the spork on which the node is running, a new metric needs to be introduced that reports the spork ID.

## Proposed Solution

What are the proposed solutions to this problem?

Introduce a new info metric to report the Spork ID. Here is an [example](https://github.com/prometheus/client_golang/blob/449b46435075e6e069e05af920fe028b941033cf/prometheus/example_metricvec_test.go#L56).

## Definition of Done

What tests must pass for this issue to be considered solved?
The new metrics gets reported when the node software is running.

This should be ideally included in the Jan 2023 spork so that by the time Metrika dashboard is made available to operators, this metric is available.

## Nice to have
If it will be great to also have the metric report other static information such as the git commit/tag of the node software.

**Comment by AlexHentschel** [comment]
To the best of my knowledge, Prometheus only supports numerical metrics. [This stackoverflow thread](https://stackoverflow.com/questions/65850083/prometheus-java-client-export-string-based-metrics) is suggesting to labels to export string values
```
version_info{version="1.23", builtOn="Windows", built_by="myUserName" gitTag="version_1.0"} = 1
```
