### ISSUE TITLE
Investigate "failed to retrieve events from execution nodes" internal RPC errors 

### ISSUE THREAD

**Issue by diaswrd** [onflow/flow-go#3601]
## Problem Definition
After initial mitigation of the 503 issues experienced on devnet38 and mainnet20 by increasing the timeout connection value between ANs and ENs, we're still experience a small subset of `rpc error: code = Canceled desc = context canceled` errors that require further investigation. Those errors happen mostly when calling the internal `GetEventsForHeightRange` method.

## Definition of Done
Number of context canceled errors doesnt go up if we decrease the timeout connection times between ANs and ENs back to 3 seconds.

## Additional Context
* [Slack thread](https://dapperlabs.slack.com/archives/C015G65HR2P/p1668039744149259)
* [Logs](https://dapperlabs.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bapp%3D%5C%22access%5C%22,%20network%3D%5C%22mainnet20%5C%22%7D%20%7C%3D%20%60rpc%20error:%20code%20%3D%20Canceled%20desc%20%3D%20context%20canceled%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D)

**Comment by j1010001** [comment]
Closing - this has not been an issue for the last couple months,  context.Cancelled means the request failed on the AN side, so it's unrelated to the execution node anyway. We will open a new ticket if this problem appears again.
