### ISSUE TITLE
any native code should be compiler with CFI Control Flow Integrity - relic

### ISSUE THREAD

**Issue by franc-crypt0-s3curity** [onflow/flow-go#3668]
## Problem Definition

What problem is this solving?
missing default security mitigation
any native code should be compiler with CFI Control Flow Integrity in production.
this is notably the case for relic.

## Proposed Solution
enable CFI at compile time
-fsanitize=cfi

## Definition of Done
all native libraries are compiled in release with CFI

**Comment by SaveTheRbtz** [comment]
@tarakby we should look into this when we start deterministically pre-compiling relic binaries instead of building them ondemand during each build. (This would require a C compiler switch/upgrade and may partially require CET support on our production machines.)

**Comment by tarakby** [comment]
Thanks @franc-crypt0-s3curity!

In our repo, we have two separate native code compilations, I guess we would need to enable CFI for both:
  - compile Relic static library (building a relic lib out of external Relic files)
  - cgo compilation of the crypto module (compiling our internal C files along with Relic static lib)
  
In clang, I think we would need to use `-fvisibility=hidden -flto -fsanitize=cfi`. I'm still not sure what flags we need to use for gcc (I believe gcc is used by our GCP instances during the production builds).

**Comment by tarakby** [comment]
moving this issue to the new repo : https://github.com/onflow/crypto/issues/16
