### ISSUE TITLE
Decide if making GRPC MaxMsgSize should be configurable via config or command line

### ISSUE THREAD

**Issue by koko1123** [onflow/flow-go#3697]
Given the issue with MaxMsgSize and the growing event sizes, we should make the variable configurable. Pending concerns about:
- security
- spork updates which make event pagination or event sizes smaller
- getting rid of the AN <> EN grpc interface altogether with Archive node

**Comment by peterargue** [comment]
I'm in favor of making it configurable, and even adding an admin command that allows modifying it without reboots. Adding both should be straight forward. I don't think there's a major security concern, especially if it's easy to update in the event someone tries to abuse a higher limit.

While we will eventually be moving away from querying ENs for much of this data, tackle the low hanging fruit.

**Comment by peterargue** [comment]
This was made configurable https://github.com/onflow/flow-go/pull/3855
