### ISSUE TITLE
[BFT] Fix message sent/received metrics

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-go#3699]
https://github.com/onflow/flow-go/pull/3375 inadvertently broke the network message sent/received metrics since the message type is not populated when the metric is emitted. Update these metrics and any others impacted by this change.

**Comment by yhassanzadeh13** [comment]
Bumping up the estimate as we are also trying to cut the dependency on the deprecated fields of a message as well and define new data structures that replace the `proto.Message` internally. In this way we only use the proto message when sending or receiving messages on wire only and not as part of internal ops.

**Comment by peterargue** [comment]
fixed by https://github.com/onflow/flow-go/pull/3675
