### ISSUE TITLE
Report account storage used change by block to prometheus

### ISSUE THREAD

**Issue by janezpodhostnik** [onflow/flow-go#3826]
## Problem Definition

We want a better view of storage growth over time

## Proposed Solution

Lets add a metric to track the total change in account storage_used per block

## Definition of Done

- new metric is being reported
- grafana has a panel for it

**Comment by janezpodhostnik** [comment]
Thinking a bit more about this... 
I can add this, but should we?
This is will count register size as the FVM understands it, which is not necessarily 1:1 with how much physical space these register take up (that depends on the storage implementation)

Maybe if we want to keep track of actual storage used by the entire state, this metric should be somewhere else.

What do you thing @j1010001 ?

**Comment by j1010001** [comment]
you are right @janezpodhostnik , it will be easier / faster to rely on checkpointing for this metric for now, closing this
