### ISSUE TITLE
Publish FLIP for Access Event Streaming API proposal

### ISSUE THREAD

**Issue by diaswrd** [onflow/flow-go#3838]
## Problem Definition
As part of the event indexing work implemented last year, a new even streaming API concept was introduced in flow-go. We need to start a FLIP to explain what are the use cases and how to use this new API, so we can gather community feedback. 

## Proposed Solution
- [] Write draft proposal for the FLIP
- [] Enter technical details and API specification
- [] Get it reviewed internally
- [] Open FLIP for discussion

## Definition of Done
FLIP is published and open for review by the community.

**Comment by bjartek** [comment]
Will this API allow us to stream more then one event at a given time? One issue that indexers have to tackle today is transactions that have "a withdraw event without a corresponding deposit event" in the same transaction.

**Comment by peterargue** [comment]
hey @bjartek here's the FLIP: https://github.com/onflow/flips/pull/73, but yes, it does include subscribing to multiple events in a single stream.
