### ISSUE TITLE
Add command to trigger stack trace dump

### ISSUE THREAD

**Issue by j1010001** [onflow/flow-go#3850]
Build admin tool functionality to dump stack trace without having to crash the node - this might help us analyze an issue when a node is blocked/unresponsive.

**Comment by j1010001** [comment]
@durkmurder you hacked together a quick solution to do this during the incident - can you add a draft PR here for reference ?

**Comment by durkmurder** [comment]
@j1010001 Here it is: https://github.com/onflow/flow-go/blob/v0.29.4-with-stacktrace/cmd/consensus/main.go#L79
