### ISSUE TITLE
How can external user access ProgramLogger?

### ISSUE THREAD

**Issue by bluesign** [onflow/flow-go#3878]
## Problem Definition

I am trying to access cadence logs ( Program Logs ) in real-time from the emulator side. After spending hours like a rat in a maze, I concluded there is no cheese for me today :) Is there a way to access this I am missing? ( maybe I can manage with writing my custom executor etc, but I am sure it is not the intended way.

**Comment by bluesign** [comment]
I hate to tag people, but any idea @janezpodhostnik @pattyshack

**Comment by janezpodhostnik** [comment]
you have to enable cadence logging https://github.com/onflow/flow-go/blob/50ae7f3ceee6adba3771b3b5c8ac4e550e257316/fvm/environment/program_logger.go#L95

then they should appear in https://github.com/onflow/flow-go/blob/242bf2cbb5b0003a1703bf6f72df990d29557f97/fvm/transaction.go#L40 or https://github.com/onflow/flow-go/blob/242bf2cbb5b0003a1703bf6f72df990d29557f97/fvm/script.go#L25

but this is only after the transaction/script. I think this is the last step after transaction execution. 

During execution, they just get stored inside `ProgramLogger`

**Comment by bluesign** [comment]
Any chance to add 

`logger.Logger().Debug().Msgf("Cadence: %s", message)` to somewhere around when appending logs, like:

https://github.com/onflow/flow-go/blob/50ae7f3ceee6adba3771b3b5c8ac4e550e257316/fvm/environment/program_logger.go#L95

in that way we can watch realtime logs with debugger and emulator.
