### ISSUE TITLE
[Storage] Refactor `badger.Cache` to use generics instead of `interface{}`

### ISSUE THREAD

**Issue by durkmurder** [onflow/flow-go#3932]
### Context

Currently `badger.Cache` operates using `interface{}` to support different types. Update the implementation to use generics.

**Comment by nozim** [comment]
#4565

**Comment by PratikDhanave** [comment]
Hi @durkmurder I like to work on this please assign this to me.
cc : @AmarildoGrembi

**Comment by durkmurder** [comment]
Implemented in https://github.com/onflow/flow-go/pull/4565
