### ISSUE TITLE
Improve remote debugger

### ISSUE THREAD

**Issue by j1010001** [onflow/flow-go#4068]
Using remote debugger is very messy right now -  we need to debug something,  it takes couple of hours to set it up. It is very important for us to debug Txs effectively.

- [ ] Remote debugger should take < 5 mins to setup
- [ ] Document the remote debugging process and share with Flow protocol + DevEx team devs

**Comment by sideninja** [comment]
After talking with @janezpodhostnik I learned there are two major use cases for this tool. 

The first is remote debugging for developers of flow-go codebase, which should be easy to do and work reliably when needed by developers. 

The second is the usage of this tool for developers on Flow blockchain to do different analyses of transactions that are already included on the network or simulate transactions that haven't been run yet. We should in this case allow different outputs based on the interest of the developer (eg developer might just be interested in computation used to know how many transactions will cost him and he should be able to easily get that number). 

This tool should probably as the final goal be accessible through Flow CLI for any developer on Flow to use and it should use Archive nodes on testnet and mainnet. 

Some starting tasks are:
- [ ] Update the dependencies and make the existing tool/code work
- [ ] Switch to usage of archive nodes for testnet (and mainnet)
- [ ] Define what are the commands from the perspective of a Flow developer
- [ ] Implement CLI commands that will allow the above, also configuration of hosts, filtering etc
- [ ] Define tasks for each command and required effort
- [ ] Discover further potential awesome features like: integrating VSCode/LS to show execution path, coverage reports, 
- [ ] Define and write documentation for flow-go developers on how to use the tool and make sure the process works smoothly

**Comment by sideninja** [comment]
Here are the first steps of the technical plan:

**Refactor transaction input**
Currently, the transaction is fetched by the transaction debugger by transaction ID as well as the block height in which the transaction is included. I propose refactoring the remote debugger from obtaining the transaction but defining an interface for fetching transactions, and then that either can be implemented to fetch existing transactions on the network, or to provide non-existing transactions to do simulations of transaction execution, which can be used for multiple purposes like optimization and computation effort analysis.

**Refactor output**
Currently, when a transaction is being executed profile builder is used, which builds a pprof profile directly as the transaction executes. The problem with this approach is that it's not well extensible, I propose refactoring to "execution holder" that only has the structures to store the data and then has different serializers of the data, one of which can be to build the execution profile, but other integrations will be used that don't require pprof profiles, one example would be outputting computation efforts of simulated transactions in CLI, so we want to have access to that data without being forced to serialize it. Similarly goes for logging interceptor, I think it would be valuable to store the data and then optionally serialize that to csv.
