### ISSUE TITLE
Node offline during Epoch Setup Phase runs into crash loop

### ISSUE THREAD

**Issue by AlexHentschel** [onflow/flow-go#4070]
We have a consensus node in a crash loop, with the following exception:

`{"level":"error","node_role":"consensus","node_id":"d98755f4ae8bef3f372889c4d7010ca784ea6da46fdde63d27ee57b2bf5efdd7","chain":"flow-mainnet","error":"could not process proposal 52020f8d2a32aa257ede3ede085743d4185ac7f02e15801f8179be678c97bdc1: failed processing current block: unexpected error in voting logic: could not produce vote: could not vote for block: could not create signature: could not get random beacon private key for view 1683865: could not retrieve random beacon private key for epoch counter 67, at view 1683865, err: key not found","time":"2023-03-21T01:12:06.088410587Z","message":"irrecoverable event loop error"}`

`{"level":"fatal","node_role":"consensus","node_id":"d98755f4ae8bef3f372889c4d7010ca784ea6da46fdde63d27ee57b2bf5efdd7","error":"could not process proposal 52020f8d2a32aa257ede3ede085743d4185ac7f02e15801f8179be678c97bdc1: failed processing current block: unexpected error in voting logic: could not produce vote: could not vote for block: could not create signature: could not get random beacon private key for view 1683865: could not retrieve random beacon private key for epoch counter 67, at view 1683865, err: key not found","time":"2023-03-21T01:12:06.089166533Z","message":"unhandled irrecoverable error"}`

Context: 
The node was likely offline for some time. They may not have even started their node during the Epoch setup phase.

**Comment by AlexHentschel** [comment]
The error states:
> could not retrieve **random beacon private key** for epoch counter 67, at view 1683865, err: **key not found**

We have a [fallback logic (code version v0.29)](https://github.com/onflow/flow-go/blob/47858e0790fd2c6d1e2d0d37fd5b2fb98b364484/consensus/hotstuff/verification/combined_signer_v2.go#L134-L136) for this case, where a consensus nodes is missing its random beacon private key.  The error indicates that this fallback did not engage, but I am not sure why.

**Comment by jordanschalm** [comment]
From vishal on Slack:
> I suggested them today to use the dynamic bootstrap flags
Delete the data folder and set these flags: --dynamic-startup-access-address=secure.mainnet.nodes.onflow.org:9001 \ --dynamic-startup-access-publickey=28a0d9edd0de3f15866dfe4aea1560c4504fe313fc6ca3f63a63e4f98d0e295144692a58ebe7f7894349198613f65b2d960abf99ec2625e247b1c78ba5bf2eae \ --dynamic-startup-epoch-phase=EpochPhaseStaking


Starting the node in the staking phase is consistent with this error.
- the node starts in the staking phase of epoch 68
- the node did not complete the DKG for epoch 67, either successfully or unsuccessfully
- therefore, the end state of the epoch 67 DKG is unset, resulting in this exception

We document that consensus/collection nodes must start in the EpochSetup phase in [the docs](https://developers.flow.com/nodes/node-operation/node-bootstrap#timing). We also set this as [the default](https://github.com/onflow/flow-go/blob/master/cmd/scaffold.go#L195). 

I think this will be resolved by this change (merged to master, but not `v0.29`): https://github.com/onflow/flow-go/pull/3950. 

We convert `ErrNotFound` to a sentinel which results in the staking key being used:
https://github.com/onflow/flow-go/blob/235ec9464e614232c370ec8830133d391898c6a0/consensus/hotstuff/signature/randombeacon_signer_store.go#L62-L67
