### ISSUE TITLE
[Access] Add heartbeat responses to event streaming API

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-go#4215]
## Problem Definition

When streaming sparse events, the Access node may search many blocks before finding the next event. This causes problems when a client disconnects since it won't know which block the AN left off on, only the last block with an event. This forces the client to rescan potentially large numbers of block each time it starts up.

## Proposed Solution

Add a periodic heartbeat response which includes the last block id/height searched. This can be identical to a regular response, just with an empty list of events. This would allow the client to track the blocks and restart closer to the actual last block searched.

## Definition of Done

Add a request option to specify the heartbeat interval `I`. When there have been `>= I` blocks since the last response, return a heartbeat.

**Comment by SaveTheRbtz** [comment]
Can we utilize http/2 PING frames instead, e.g. via [google.golang.org/grpc/keepalive](https://pkg.go.dev/google.golang.org/grpc/keepalive)?

**Comment by peterargue** [comment]
Yea, exactly.
https://github.com/onflow/flow/blob/master/protobuf/flow/executiondata/executiondata.proto#L44-L46
https://github.com/onflow/flips/blob/main/protocol/20230309-accessnode-event-streaming-api.md#responses-and-heartbeats
