### ISSUE TITLE
[Optimization] Multi-state HeroCache with Caller Supplied Arrays and Custom Eviction Strategies

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-go#4272]
## Problem Definition

The current HeroCache implementation supports a default eviction strategy. However, it would be beneficial to provide more flexibility by allowing users to supply their own eviction strategies or opt for no eviction at all. This could make the HeroCache more versatile and reusable for other algorithms, such as MTrie.

## Proposed Solution

Extend the HeroCache to support multi-state scenarios and allow callers to provide their own arrays and eviction strategies. Implement a callback mechanism to enable custom eviction or disable it entirely.

### Multi-state HeroCache design
1. Maintain the existing state-based HeroCache design.
2. Allow callers to provide their own arrays to be used with the HeroCache.
3. Allow callers to supply custom eviction strategies using a callback mechanism.
4. Provide an option to disable eviction entirely.

### Benefits
Implementing a multi-state HeroCache with caller-supplied arrays and custom eviction strategies will:
1. Increase flexibility and customization options for users.
2. Make the HeroCache more versatile and reusable for other algorithms, such as MTrie.
3. Allow users to optimize their caching strategies based on specific use cases.

### Next Steps
1. Design and implement the multi-state HeroCache with support for caller supplied arrays and custom eviction strategies.
2. Update the current implementation to incorporate the new features.
3. Test the updated implementation to ensure it maintains the existing functionality and supports custom eviction strategies.
5. Document the changes made in the codebase, including the new multi-state design and custom eviction strategies.
6. Review the new implementation for adherence to best practices and coding standards.
7. Integrate the optimized implementation into the main codebase.

## Definition of Done

1. The code should be refactored to support multi-state HeroCache with caller supplied arrays and custom eviction strategies.
2. The existing functionality should be maintained, and all tests should pass.
3. Proper documentation should be provided to explain the new implementation.
4. The code should adhere to best practices and coding standards of the Flow codebase.
5. The implementation should be supported by adequate testing.

**Comment by kozlovb** [comment]
This is a first naive proposal. Please advise if our understanding is aligned with the issue's idea.

We are going to take list type from the [4273  github issue](https://github.com/onflow/flow-go/issues/4273):

```
// 
const ( // iota is reset to 0
  stateFree uint32 = iota
  stateUsed
)
list[stateFree].size = 3 // double linked list 'Free' has 3 items
list[stateFree].head = 0
list[stateFree].tail = 2
list[stateUsed].size = 0 // double linked list 'Used' is empty
```

Here is a tentative interface proposal: 

```
// We pass an interface to a policy into the HeroPool.
func NewHeroPool(sizeLimit uint32, ejectionPolicy EvictionPolicy) *Pool

type EvictionPolicy interface {

// Called in the NewHeroPool before EvictionPolicy is provided to Pool.
// sizeLimit - is the same as sizeLimit of NewHeroPool
init(sizeLimit uint)

// Returns false if eviction is needed. In this case the returned EIndex is like a hint to an element
// that has to be evicted.
// Returns true if no eviction is needed. EIndex can be then directly used.
toBeAdded() (bool, EIndex)

// Called when an eviction is needed. Returns false if no eviction policy is used.
// If true is returned, means element can be invalidated in the pool and this index can be used 
// to store a new one.
tryEvict(index EIndex) (bool)

// Called after the element is added.
onAdded(index EIndex)

// Called on each get, as may be certain implementations of EvictionPolicy would maintain 
// a list of recently used elements. 
onGet(index EIndex)

// may be onHead if we consider Pool.Head as a get API.
}
```

The concrete implementation of Eviction policy may be based on any data structure, but here is an example based on lists. 
We've discussed previously that allocations on the heap should be avoided. For this reason, in addition to lists an EvictionPolicy will hold an array of links. Links would be no longer part of the poolEntity struct.

```
type StateImpl uint32

const (
    stateFree State = iota
	stateUsed
	stateFree
)

type EvictionPolicyImpl struct {

sizeLimit uint

// here we may have several arrays of links, depending on if we need to allow 
// an item to be in more than one list at the time. But lets starts just wih one
nodes: []link

lists: make([]list, sizeOfStateImpl)
}

// Implementation of the interface methods ...

}```
