### ISSUE TITLE
Optimize HeroCache to support generic types and improve performance

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-go#4275]
### Background
HeroCache currently uses `flow.Identifier` as the key and entity as the value with the `flow.Entity` interface being the generic data structure. While this design ensures self-certifying correctness, it might be limiting the potential use cases of the cache and causing performance issues.

1. Limited support for generic types: HeroCache currently supports only the `flow.Entity` interface, which may not be suitable for other use cases and data structures (e.g., MTrie nodes, TCP connection management structures).

2. Performance concerns: Supporting the generic Golang `interface {}` might introduce performance penalties due to the extra layer of interface redirection.

HeroCache needs to evolve to support generic types without sacrificing performance and this task aims to deliver that.

## Proposed Solution

The issue explores possible alternatives for supporting generic types in HeroCache while considering the impact on performance and maintaining the self-certifying nature of the Flow codebase.

Investigate and implement an optimized version of HeroCache that supports generic types without compromising performance. This may involve:
1. Evaluating the performance impact of using the generic Golang `interface {}` and determining if the penalty is acceptable.
2. Exploring alternative approaches for implementing generic type support without using `interface {}` and without incurring performance penalties, e.g., native Golang generic type. 
3. Ensuring that the self-certifying correctness feature of the Flow codebase is not compromised during the refactoring process.

Before moving forward with any implementation, it is crucial to evaluate different approaches, considering their impact on performance and the codebase's self-certifying correctness. If you have any suggestions or questions or would like to contribute to this issue, please feel free to comment below or reach out to the project maintainer: @yhassanzadeh13 

## Definition of Done

1. HeroCache supports generic types, expanding its usability for different data structures and use cases.
2. Regression performance testing developed that attests to no performance degradation from the original implementation when switching to support generic types, i.e., the performance of the new HeroCache implementation is on par with or better than the current implementation.
3. The self-certifying correctness feature of the Flow codebase is preserved.
4. The changes are well-documented, including any trade-offs or design decisions.

## Related Issues / PRs
https://github.com/onflow/flow-go/pull/1778

**Comment by nozim** [comment]
@franklywatson I'd like to pick this up if there is no work has been done here.
