### ISSUE TITLE
Investigate Excessive Heap Usage in LibP2P DHT for Collection Nodes

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-go#4277]
## Context

Heap usage for collection nodes has been observed to be excessive, particularly regarding the Distributed Hash Table (DHT) in the libp2p library. The high heap usage could negatively impact the network's overall performance and efficiency.

## Problem Definition

Excessive heap usage due to DHT activity in the libp2p library might impact network performance and resource consumption. Ideally, methods like 'Unmarshal' should not rely on the heap to minimize resource usage and optimize performance.

```
11840496  6.60%  6.60%   15182984  8.46%  github.com/libp2p/go-libp2p-kad-dht/pb.(*Message_Peer).Unmarshal
   5363273  2.99% 34.02%    5363273  2.99%  github.com/libp2p/go-libp2p-kad-dht/pb.peerInfoToPBPeer
   4030645  2.25% 43.58%   11982645  6.68%  github.com/libp2p/go-libp2p-kad-dht.NewPeerKadID (inline)
   4015041  2.24% 48.06%   13528920  7.54%  github.com/libp2p/go-libp2p-kad-dht/pb.PBPeersToPeerInfos
   3440742  1.92% 53.96%    9513879  5.30%  github.com/libp2p/go-libp2p-kad-dht/pb.(*Message_Peer).Addresses
   3342488  1.86% 55.82%    3342488  1.86%  github.com/libp2p/go-libp2p-kad-dht/pb.(*byteString).Unmarshal (inline)
   3334368  1.86% 57.68%   20875082 11.63%  github.com/libp2p/go-libp2p-kad-dht.(*query).queryPeer
   2482357  1.38% 59.06%    2482357  1.38%  github.com/libp2p/go-libp2p-kad-dht/qpeerset.(*QueryPeerset).GetClosestNInStates
   2009798  1.12% 62.67%   17192782  9.58%  github.com/libp2p/go-libp2p-kad-dht/pb.(*Message).Unmarshal
   1130536  0.63% 68.40%    1917017  1.07%  github.com/libp2p/go-libp2p-kad-dht/internal/net.(*peerMessageSender).ctxReadMsg
    921670  0.51% 72.41%   24192537 13.48%  github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).handleNewMessage
    917554  0.51% 72.92%    2185191  1.22%  github.com/libp2p/go-libp2p-kad-dht/providers.(*ProviderManager).GetProviders
    652659  0.36% 75.01%   20980197 11.69%  github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).findProvidersAsyncRoutine.func1
    615086  0.34% 75.35%    5978359  3.33%  github.com/libp2p/go-libp2p-kad-dht/pb.RawPeerInfosToPBPeers
    438871  0.24% 76.75%    8920666  4.97%  github.com/libp2p/go-libp2p-kad-dht.NewPeerKadIDSlice
    382310  0.21% 77.20%    1179693  0.66%  github.com/libp2p/go-libp2p-kad-dht.NewKeyKadID (inline)
    369848  0.21% 77.41%   11644440  6.49%  github.com/libp2p/go-libp2p-kad-dht.NewLookupUpdateEvent
    360464   0.2% 77.61%    6252819  3.48%  github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).nearestPeersToQuery
    344084  0.19% 77.80%    2670701  1.49%  github.com/libp2p/go-libp2p-kad-dht.NewLookupEvent
    311319  0.17% 78.16%    6715301  3.74%  github.com/libp2p/go-libp2p-kad-dht/internal/net.(*messageSenderImpl).SendRequest
    299349  0.17% 78.32%    6552168  3.65%  github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).betterPeersToQuery
    294948  0.16% 78.49%    4466064  2.49%  github.com/libp2p/go-libp2p-kad-dht/internal/net.(*peerMessageSender).SendRequest
    188427  0.11% 79.19%    3971338  2.21%  github.com/libp2p/go-libp2p-kad-dht.(*query).spawnQuery
    103774 0.058% 79.93%   19266011 10.74%  github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).runLookupWithFollowup
     70326 0.039% 80.31%     960560  0.54%  github.com/libp2p/go-libp2p-kad-dht/qpeerset.(*QueryPeerset).TryAdd
     53523  0.03% 80.66%   19448428 10.84%  github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).findProvidersAsyncRoutine
     39486 0.022% 80.73%   11466738  6.39%  github.com/libp2p/go-libp2p-kad-dht.(*query).updateState
     39324 0.022% 80.75%   17978187 10.02%  github.com/libp2p/go-libp2p-kad-dht.(*query).run
```

## Proposed Solution

1. Investigate the source of excessive heap usage in the libp2p DHT for collection nodes.
2. Identify potential optimizations or alternative implementations to reduce heap usage.
3. Implement the identified optimizations and measure the impact on heap usage and overall performance.

### Benefits
Addressing excessive heap usage in the libp2p DHT for collection nodes will yield the following benefits:
1. Reduced resource consumption, leading to better network performance and efficiency.
2. Increased stability and reliability of the collection nodes.
3. Minimized potential bottlenecks in the network.

### Next Steps
1. Investigate the source of excessive heap usage in the libp2p DHT for collection nodes.
2. Research potential optimizations or alternative implementations to address the issue.
3. Implement the chosen optimization(s) or alternative(s) in a testing environment.
4. Measure the impact of the changes on heap usage and overall performance.
5. Analyze the results and make an informed decision on whether to integrate the changes into the main codebase.
6. Update the documentation to reflect the changes made in the codebase, if applicable.
7. Ensure that all tests pass and the code adheres to the Flow coding standards.
8. Review and integrate the optimized or alternative implementation, if deemed suitable, into the libp2p node.

## Definition of Done

The following criteria should be met:
1. The source of excessive heap usage in the libp2p DHT for collection nodes has been identified.
2. Potential optimizations or alternative implementations have been proposed and evaluated.
3. The chosen optimizations or alternative implementations have been implemented.
4. The impact of the changes on heap usage and overall performance has been measured and validated.
5. The code should be properly documented and conform to the Flow coding standards.
6. All tests related to the libp2p DHT and collection nodes should pass.
7. The proposed solution should not break any existing functionality or use cases of the libp2p node.

## Actions Needed Before Submitting

Update ticket status using the following (remove this section once ticket created)

- What *workstream* does this ticket deal with? Find the appropriate 'S-' label and add that label.
- Is it a specific *'type'* of ticket (ex: bug, documentation)? If yes, add that label as well.
- Is this ticket related to an *overarching theme* (ex: architecture, performance)? If yes, add that label as well.
- Add any/all *descriptive characteristic* labels needed (ex: Needs Estimation, Needs Test Cases).
- Now we should determine what *release* this ticket is associated with. If none, leave it blank. If it is associated with a specific release, please add it to the appropriate release.
- If this ticket is associated with a release, we want to assign it a *level of importance* within that release. These labels follow the standard [MoSCoW method](https://en.wikipedia.org/wiki/MoSCoW_method) rules. We want to look at releases and then the importance of tickets within those specific releases. So the MoSCoW label is ONLY valid when it is taken in conjunction with its release.
- Assign this ticket a *priority level* (High, Medium, Low) via the appropriate label. These labels control the importance of the ticket within the sprint. For example, all `P-High` tickets should be worked on first, then `P-Medium`, then `P-Low`. This gives us an easy way to identify the order of priority for tickets within a specific sprint.

**Comment by peterargue** [comment]
DHT was disable on collection nodes https://github.com/onflow/flow-go/pull/4800
