### ISSUE TITLE
[Networking] Let libp2p nodes negotiate for stream compression

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-go#4278]
## Context
In Flow, Libp2p nodes currently can negotiate for stream compression when reading and writing on a connection. Two modes of compression are currently implemented: gzip and no-compression. However, there is a need to explore more efficient options to optimize network performance and bandwidth utilization further.

See the current unicast manager implementation that handles the negotiation: https://github.com/dapperlabs/flow-go/tree/master-private/network/p2p/unicast

## Problem Definition

While the current implementation allows stream compression negotiation, it does not enforce mandatory compression for staked nodes. This leaves the network vulnerable to resource exhaustion attacks from byzantine nodes that may choose no compression or inefficient compression.

## Proposed Solution

Investigate and implement more efficient stream compression algorithms while making stream compression mandatory for staked nodes. This will improve network performance and protect against potential resource exhaustion attacks.

1. Research and identify more efficient stream compression algorithms.
2. Implement the chosen algorithm(s) alongside the existing gzip and no-compression modes.
3. Make stream compression mandatory for staked nodes to ensure network stability and security.

### Benefits
By implementing more efficient stream compression algorithms and making compression mandatory for staked nodes, the following benefits can be achieved:

1. Improved network performance and bandwidth utilization.
2. Enhanced security and stability by mitigating resource exhaustion attacks.
3. Greater overall efficiency and resource management in the network.

### Next Steps
1. Research and identify more efficient stream compression algorithms.
2. Evaluate the potential impact of integrating the alternative algorithms on the existing codebase.
3. Implement the chosen algorithm(s) in a testing environment.
4. Measure the impact of the changes on network performance and bandwidth utilization.
5. Analyze the results and make an informed decision on whether to integrate the changes into the main codebase.
6. Update the documentation to reflect the changes made in the codebase, if applicable.
7. Ensure that all tests pass and the code adheres to the Flow coding standards.
8. Review and integrate the optimized implementation, if deemed suitable, into the main codebase.

## Definition of Done

1. Research and identify more efficient stream compression algorithms.
2. Implement the chosen algorithm(s) in the libp2p nodes stream compression negotiation process.
3. Make stream compression mandatory for staked nodes (communicate with @yhassanzadeh13 and @kc1116 regarding integrating the compression requirement with scoring mechanism). 
4. Measure the impact of the changes on network performance and bandwidth utilization.
5. The code should be properly documented and conform to the Flow coding standards.
6. All tests related to the stream compression negotiation should pass.
7. The implemented changes should not break any existing functionality or use cases.

**Comment by UlyanaAndrukhiv** [comment]
Investigation for the issue on [Google Doc](https://docs.google.com/document/d/13VyIweOFCRiSAmhCLkbJJ8MPqCIZcclBcatomnmiKK0/edit?usp=drive_link)
