### ISSUE TITLE
[Networking] LibP2PNode Interface into Smaller, More Modular Interfaces

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-go#4282]
## Context
The current [LibP2PNode interface](https://github.com/onflow/flow-go/blob/master/network/p2p/libp2pNode.go) comprises a large number of methods that cater to various functionalities related to the libp2p node. This leads to a high degree of coupling between the components that utilize this interface and the libp2p node implementation. To mitigate this coupling and enhance modularity, we should contemplate refactoring the interface.

## Problem Definition

The existing LibP2PNode interface combines several responsibilities, which results in tight coupling between the components that use this interface and the libp2p node implementation. This can lead to difficulties in testing, maintaining, and extending the codebase.

## Proposed Solution

We suggest separating the LibP2PNode interface into smaller, more focused interfaces based on functionality, such as:
- `PeerConnectionManagement` - for managing connections with other peers.
- `PubSubManagement` - for handling publish/subscribe messaging.
- `RoutingManagement` - for managing routing tables and peer discovery.
Utilize dependency injection or composition to supply only the necessary interfaces to the components that use the libp2p node.

### Benefits
Refactoring the LibP2PNode interface into smaller, more modular interfaces will yield the following benefits:
- Enhanced modularity and flexibility in the use of the libp2p node.
- Reduced coupling between components and the libp2p node implementation.
- Simplified maintenance and testing of the libp2p node.
- Improved adherence to the Single Responsibility Principle (SRP) and Separation of Concerns (SoC) design principles.
- Increased readability and understandability of the code.

### Next Steps
- Analyze the current LibP2PNode interface and identify distinct functionalities that can be separated into smaller interfaces.
- Design and implement the new, smaller interfaces based on identified functionalities.
- Refactor the existing components that use the LibP2PNode interface to utilize the new interfaces.
- Ensure that all tests pass and the code adheres to the Flow coding standards.
- Update documentation to reflect the changes made in the codebase.
- Review and integrate the refactored interface into the libp2p node implementation.

## Definition of Done

- The LibP2PNode interface should be separated into smaller interfaces based on functionality.
- All tests related to the LibP2PNode interface should pass with the refactored interface.
- The code should be properly documented and conform to the Flow coding standards.
- The refactored interface should not break any existing functionality or use cases of the libp2p node.
- The new interfaces should be properly tested and integrated into the libp2p node implementation.

**Comment by nozim** [comment]
https://github.com/onflow/flow-go/pull/4630

**Comment by nozim** [comment]
https://github.com/onflow/flow-go/pull/4630

**Comment by nozim** [comment]
I believe this can be closed since the PR is merged https://github.com/onflow/flow-go/pull/4630
