### ISSUE TITLE
Analyze gRPC and REST Access APIs to confirm inconsistencies

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-go#4301]
## Problem Definition

There are [known](https://github.com/onflow/flow-go/issues/3304) differences between gRPC vs REST versions of the Access API. It's not known what the scope and nature of these differences are. Do they differ in spec, or functionally at runtime? Are some methods not mapped 1:1 at all? Were certain REST API design choices made to benefit FCL integration? This analysis will make clear any unknowns. It will inform a future Flow objective to simplify the API layer with gRPC only base API and REST served through automatic API generation, eg: gRPC-Web (https://grpc.io/blog/state-of-grpc-web/, https://github.com/grpc-ecosystem/grpc-gateway)

## Definition of Done

The outputs of this analysis effort shall 
* Share a report document (Google Doc) linked to by a forum post which clearly summarizes 
  * Technical details on structure or other differences in API specifications, request/response schemas, functional or other inconsistencies
  * Supporting information as required to clarify if a difference impacts the end-user experience, or poses other risks or challenges for users or integrators 
  * Document node specific differences in provision/support of the Access API
  * If possible, we invite the contributor to detail changes needed to restore consistency documented in a "Remedies/mitigations" section for each API difference 
* Integrate this refreshed understanding of the APIs through a PR improving code level technical documentation, only for surface area not in question or under discussion

**Comment by SaveTheRbtz** [comment]
nit: you can consider using Envoy for grpc transcoding instead of grpc-gateway, since the former is already a part of Access Node setup (cc: @sjonpaulbrown).

**Comment by bluesign** [comment]
> There are https://github.com/onflow/flow-go/issues/3304 differences between gRPC vs REST versions of the Access API.

This issue seems not about that though. as stated by ( As I indicated in slack, I don't observe this behavior when querying access.devnet.nodes.onflow.org. ) I think this is some problem with observer only. 

> nit: you can consider using Envoy for grpc transcoding instead of grpc-gateway

not sure envoy is enough there. REST API has more features like `filter` etc.
