### ISSUE TITLE
Automated Block Rate Controller for Epoch Timing

### ISSUE THREAD

**Issue by jordanschalm** [onflow/flow-go#4322]
## Context

This epic captures issues related to controlling block rate in order to automated targeting particular epoch switchover times. See the [design document in Notion](https://www.notion.so/dapperlabs/Automated-Block-Rate-Epoch-Timing-4dbcb0dab1394fc7b91966d7d84ad48d?pvs=4) for context and details.

**Comment by AlexHentschel** [comment]
🎉
