### ISSUE TITLE
BlockRateController: Create component skeleton

### ISSUE THREAD

**Issue by jordanschalm** [onflow/flow-go#4323]
## Context

See https://www.notion.so/dapperlabs/Automated-Block-Rate-Epoch-Timing-4dbcb0dab1394fc7b91966d7d84ad48d?pvs=4.

## Definition of Done

- Create new component `BlockRateController`
- Create config structure with atomic fields for admin-updatable fields
- Create event handlers, as defined in Notion doc

**Comment by AlexHentschel** [comment]
PR https://github.com/onflow/flow-go/pull/4332
