### ISSUE TITLE
BlockRateController: Add metrics collection

### ISSUE THREAD

**Issue by jordanschalm** [onflow/flow-go#4325]
## Context
See https://www.notion.so/dapperlabs/Automated-Block-Rate-Epoch-Timing-4dbcb0dab1394fc7b91966d7d84ad48d?pvs=4

## Definition of Done

Add metrics as defined in notion doc. 
- `block_rate_delay` - the actual block rate delay being used by the node (gauge)
- `observed_ewma_view_rate` - observed view rate (gauge)
- `estimated_error_s` - the estimated deviation from target switchover time (gauge)

**Comment by AlexHentschel** [comment]
implemented by PR https://github.com/onflow/flow-go/pull/4386
