### ISSUE TITLE
BlockRateController: Determine tuning parameters for compensation function

### ISSUE THREAD

**Issue by jordanschalm** [onflow/flow-go#4327]
## Context
See https://www.notion.so/dapperlabs/Automated-Block-Rate-Epoch-Timing-4dbcb0dab1394fc7b91966d7d84ad48d?pvs=4

The ongoing tuning work is documented in https://www.notion.so/dapperlabs/ID-controller-for-block-rate-delay-cc9c2d9785ac4708a37bb952557b5ef4?pvs=4. The plan is to:
- Download Mainnet data for actual block rate delays between blocks
- Determine a stochastic model corresponding to the observed block rate data
- Upon completion of the PID controller, tune its parameters by training it using the model to produce training inputs for the controller

## Definition of Done
When this is done, we should have values for N, KP, KI, KD (the tuning parameters for the PID controller) which we are comfortable deploying to Mainnet.

**Comment by AlexHentschel** [comment]
Results:
* Statistical model: 
   * python code: https://github.com/dapperlabs/flow-internal/blob/master/analyses/pacemaker_timing/2023-05_Blocktime_PID-controller/block_receive_delay.py
   * writeup of results: https://www.notion.so/dapperlabs/ID-controller-for-block-rate-delay-cc9c2d9785ac4708a37bb952557b5ef4?pvs=4
* controller tuning
   * python code: https://github.com/dapperlabs/flow-internal/blob/master/analyses/pacemaker_timing/2023-05_Blocktime_PID-controller/controller_tuning_v01.py
   * writeup of tuning results and implementation overview: https://www.notion.so/dapperlabs/Cruise-Control-Automated-Block-Rate-Epoch-Timing-4dbcb0dab1394fc7b91966d7d84ad48d?pvs=4
