### ISSUE TITLE
Ping Execution and Collection nodes when serving Access API Ping Response

### ISSUE THREAD

**Issue by vishalchangrani** [onflow/flow-go#4517]
## Problem Definition

What problem is this solving?

Recently, there was a [sev-2 issue](https://www.notion.so/dapperlabs/Testnet-API-broken-after-epoch-transition-6dc425acc379416fad3986655c2e72d6) on devnet45 which was caused because the network addresses were not updated after the devnet spork. The problem could have been detected earlier if the Access node Ping endpoint was called once every minute or so and it in turn pinged the Collection and Execution nodes with their on-chain addresses.

## Proposed Solution

What are the proposed solutions to this problem?

The Access node, when responding to the ping request, also pings the Collection and Execution node with their on-chain addresses.

## Definition of Done

What tests must pass for this issue to be considered solved?
Happy path - Access node pings a collection node and an execution node successfully.
Unhappy path - Access node is able to detect that collection node and/or execution nodes are not available.

## Actions Needed Before Submitting

Update ticket status using the following (remove this section once ticket created)

- What *workstream* does this ticket deal with? Find the appropriate 'S-' label and add that label.
- Is it a specific *'type'* of ticket (ex: bug, documentation)? If yes, add that label as well.
- Is this ticket related to an *overarching theme* (ex: architecture, performance)? If yes, add that label as well.
- Add any/all *descriptive characteristic* labels needed (ex: Needs Estimation, Needs Test Cases).
- Now we should determine what *release* this ticket is associated with. If none, leave it blank. If it is associated with a specific release, please add it to the appropriate release.
- If this ticket is associated with a release, we want to assign it a *level of importance* within that release. These labels follow the standard [MoSCoW method](https://en.wikipedia.org/wiki/MoSCoW_method) rules. We want to look at releases and then the importance of tickets within those specific releases. So the MoSCoW label is ONLY valid when it is taken in conjunction with its release.
- Assign this ticket a *priority level* (High, Medium, Low) via the appropriate label. These labels control the importance of the ticket within the sprint. For example, all `P-High` tickets should be worked on first, then `P-Medium`, then `P-Low`. This gives us an easy way to identify the order of priority for tickets within a specific sprint.

**Comment by peterargue** [comment]
@vishalchangrani do you mean the grpc `Ping` endpoint? I'd a little concerned about the abuse potential of allowing a user to send a single grpc request which cascades into potentially hundreds of requests on the backend.

**Comment by peterargue** [comment]
@vishalchangrani I'm going to close this issue out as I think this approach would create a DoS vector against the AN. Feel free to reopen if you want to discuss this further.
