### ISSUE TITLE
[Access] Move node unavailable error handling to interceptor

### ISSUE THREAD

**Issue by koko1123** [onflow/flow-go#4526]
## Problem

The access nodes have repeated [error handling](https://github.com/onflow/flow-go/pull/4244/files#r1173662919) for unavailable execution/collection/archive nodes. 

## Solution

Move this type of error handling to an interceptor or the client library

**Comment by peterargue** [comment]
FWIW, this is getting refactored in https://github.com/onflow/flow-go/pull/4496
