### ISSUE TITLE
Execution node uploader only uploads last event instead of all events.

### ISSUE THREAD

**Issue by koko1123** [onflow/flow-go#4558]
## Problem
In the code [here:](https://github.com/onflow/flow-go/blob/70a431d8f23a6ac0641eed69be74e48af0179c1b/engine/execution/ingestion/uploader/model.go#L33-L35) 
Only the last event is being written and uploaded to GCP

[Flow discord link](https://discordapp.com/channels/613813861610684416/1108968095982293002/1128363139453431869)

`curl -s "https://storage.googleapis.com/flow_public_mainnet23_execution_state/cb0c4b6cabef767b50fedda3d11da2308f49249818b87d2d5f57b467c9c96e73.cbor" | strings | grep "A\." | grep "@x" | sort | uniq -c`

**Comment by Kay-Zee** [comment]
I'm guessing we will have to re-upload everything from this current spork once this is finished? is that included in this issue or does this just cover the bug fix?

**Comment by koko1123** [comment]
> I'm guessing we will have to re-upload everything from this current spork once this is finished? is that included in this issue or does this just cover the bug fix?

We would have to backfill this data. OR we could switch over to the exec streaming API here: https://github.com/onflow/flow-archive/pull/89 and discard this functionality entirely
