### ISSUE TITLE
[Access] Cache unknown TX lookups

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-go#4585]
## Problem Definition

When a user calls `GetTransactionResult` for a transaction ID that doesn't exist in the Access node's database, the node will query  the configured list of historic access nodes for the result.
https://github.com/onflow/flow-go/blob/d9ae9eb870940f01ad434230d6d37d160ebfc318/engine/access/rpc/backend/backend_transactions.go#L247-L264

This is a UI improvement that was added to simplify searching for transaction results across spork boundaries.

It also can cause unnecessary latency for the user and load on the Access node, when a user queries for a brand new transaction. A common usage pattern is for a user to submit a transaction, then immediately start polling for the result. In the time before that transaction is included in a finalized block and indexed by the AN (typically 4-8 seconds), queries will be forwarded to the historic nodes. This can add seconds of latency to each request.

## Proposed Solution

Add a cache to the `GetTransactionResult` endpoint that tracks search results from the historic nodes. The list of available tx on the historic nodes never changes, so these results can be reliably cached.

In the above code snippet, a cache check could be added within the conditional if a `codes.NotFound` error was received. If a cached value existed, return it immediately. Otherwise, query the historic nodes and cache the result.

A LRU caching scheme would work well here, and relatively small cache size should work fine. The goal is to capture most of the cases where users are querying for new tx.

## Definition of Done

* A tx result cache is added in the case where the tx was not available in the local db.
* The cache's max size is configurable using cli flags
* The cache is only used when:
    * historic nodes are searched
    * either a result is found, or all nodes return `codes.NotFound`
* There are metrics to track cache usage and hit rate
* There are unit and functional tests covering the new code paths.

**Comment by nozim** [comment]
@peterargue thanks for the context. Will have a look on this.
