### ISSUE TITLE
Add Keys option to accounts gRPC endpoint

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-go#4592]
## Problem Definition

https://github.com/onflow/flow-go/issues/4564 adds support for a new Account keys endpoint to the REST API. To keep the APIs consistent, add endpoints to support the same queries to the gRPC API.

## Proposed Solution

Add `GetAccountKeyAtLatestBlock` and `GetAccountKeyAtBlockHeight` which take the following arguments:
* `bytes address`
* `uint32 key_index`
* `uint64 block_height` (only for `GetAccountKeyAtBlockHeight`)
* `entities.Metadata metadata`

and return the `entities.AccountKey` for the key belonging to that provide address at `key_index`.

## Definition of Done

* The new methods are added to the AccessAPI protobuf
* Endpoints are implemented within the access api on access/observer nodes
* Endpoints are integrated with api proxy code and interfaces throughout flow-go.
* Unit and functional tests cover the new endpoints

**Comment by m-Peter** [comment]
As I have already done related work for https://github.com/onflow/flow-go/issues/4564, I am assigning this to myself :pray:

**Comment by peterargue** [comment]
This will be addressed by https://github.com/onflow/flow-go/issues/5999
