### ISSUE TITLE
[Script Execution] State Data Indexer Module

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-go#4638]
Implement an execution state data indexer module, that ingests data from Execution State Sync APIs and stores them in the Execution Data Index module. 

Define an interface for data execution db so we can keep a simple in-memory implementation for registers db.

Use jobqueue internally to process new available data from the execution state sync.

**Comment by peterargue** [comment]
implemented by https://github.com/onflow/flow-go/pull/4653
