### ISSUE TITLE
[Script Execution] Execution Data Index

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-go#4639]
Implement execution data database using Pebble. 

The implementation should satisfy the [ReadOnlyExecutionState](https://github.com/onflow/flow-go/blob/567d5485204d0e46f0e32e5a41bbeac06d58b731/engine/execution/state/state.go#L24) interface as it's used by the computation manager.

A simple design proposal schema:
![Screenshot 2023-08-25 at 19 07 46](https://github.com/onflow/flow-go/assets/75445744/01dbf8b1-df86-4e6c-8520-b5bcbedded5d)

**Comment by koko1123** [comment]
overlaps with https://github.com/onflow/flow-go/issues/4606
