### ISSUE TITLE
[Access] Getting account from local storage returns not found error

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-go#4824]
When getting an account from local storage on an Access node, a `NotFound` error is returned for accounts with no contracts deployed. e.g.
```
rpc error: code = NotFound desc = account with address 232f1bc00d90a1c2 not found: failed to get account (232f1bc00d90a1c2) at block (18644be942ea58275cfc9523bcf359816dd72559c0c3c793c1e930f68689980e): cannot get account, this error usually happens if the reference block for this query is not set to a recent block: cannot get deployed contract names: failed to read 232f1bc00d90a1c2/#636f6e74726163745f6e616d6573: [Failure Code: 2002] ledger returns unsuccessful: get register failed: key not found
```

This points to an error at this line:
https://github.com/onflow/flow-go/blob/043570794069a876072d50de4dc03bbd34f063c7/fvm/environment/accounts.go#L610-L613

**Comment by janezpodhostnik** [comment]
This is a ledger failure... something in the ledger returned an error.
for accounts with no contracts, the ledger should return an empty payload (because nothing was saved to the contracts register yet) but the ledger returns an error instead.

**Comment by sideninja** [comment]
Yes we are, will change that behavior after I can confirm it's not expected somewhere else. 
I guess with that PR I should also update the comment defining this behaviour on ledger? https://github.com/onflow/flow-go/blob/6af8b17ff1eee9ec68dc20776e08c969e91430c5/ledger/ledger.go#L34 or you think that's no the right place?

**Comment by sideninja** [comment]
Actually it's already commented here https://github.com/onflow/flow-go/blob/32458411b33a899a6d3493955a2b58c520e71fa4/fvm/storage/snapshot/storage_snapshot.go#L11

**Comment by j1010001** [comment]
Can we add a test for this as well ?
