### ISSUE TITLE
[Access] Add endpoint to get protocol snapshot from any block

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-go#4869]
## Problem Definition

Currently, Access nodes have a `GetLatestProtocolStateSnapshot` endpoint that returns the protocol state snapshot from the most recently finalized block at the time it was called. This is typically used to generate the root-protocol-state-snapshot used to bootstrap a new node.

This method lacks control of which specific block to use as the root, limiting it's usefulness. A few usecases where it would be helpful to specify the block
* Access nodes need the execution state checkpoint to match the root snapshot. Checkpoints are generated by Execution nodes periodically, but not on a set schedule. To simplify bootstrapping, an AN could get a checkpoint from somepoint after it was staked, then generate a root snapshot that matches its block.
* Access and Observer nodes sync blocks starting from their root snapshot. Allowing custom blocks gives more flexibility for operators to bootstrap. For example, bootstrapping using a block before the network went into EFM.
* Inspecting protocol state at a particular point in time. For instance, it's often useful for debugging to see which nodes where in the identity table at a point in time.

## Proposed Solution

Introduce new methods `GetProtocolStateSnapshotByBlockID`, `GetProtocolStateSnapshotByHeight` that return the snapshot from the specified block if that block is finalized.

## Definition of Done

* There are 2 new methods defined in the AccessAPI protobuf: `GetProtocolStateSnapshotByBlockID`, `GetProtocolStateSnapshotByHeight`
* These 2 new methods are implemented in the AccessAPI in flow-go
* There are unit and integration tests covering the new endpoints

**Comment by jordanschalm** [comment]
I'm all for it. There is a CLI util to do this already that we can use as a reference for the endpoint: https://github.com/onflow/flow-go/blob/a98da01683497eaca21a1e3ee3f62c4af797e91b/cmd/util/cmd/read-protocol-state/cmd/snapshot.go#L1

**Comment by AlexHentschel** [comment]
Regarding `GetProtocolStateSnapshotByBlockID`: lets make sure that we don't generate snapshots for non-finalized blocks. I would guess that the logic for generating the snapshot already contains a corresponding safety check, but we should confirm that this is the case
