### ISSUE TITLE
[Flow EVM] adding `toAttoFlow` method to `EVM.Balance`

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-go#4961]
We need to add `toAttoFlow` function to `EVM.Balance` as described in the flip.

**Comment by ramtinms** [comment]
@turbolent I did a low confidence estimate for this issue, but would like to know your view about these two items in this issue?

**Comment by turbolent** [comment]
- Add `EVM.Balance.toAttoFlow`: This should be very simple
- `EVM.BridgedAccount.withdraw`: This is not needed/applicable anymore, given that `EVM.BridgedAccount.deposit` changed to not destroying the deposited vault anymore, to prevent the total supply being adjusted, while funds are "stored on the EVM side".

**Comment by ramtinms** [comment]
Thanks for clarification, dropped the second item from the list and updated the estimate
