### ISSUE TITLE
[Storehouse] Benchmark RegisterStore

### ISSUE THREAD

**Issue by zhangchiqing** [onflow/flow-go#5101]
# Background
When getting register from storehouse, it acquires a read lock, which will be blocked when saving registers after finishing executing a block, or pruning registers after finalizing a block. 

# Goal
Benchmark the conflict between getting register and saving/pruning registers, and understand the impact.

# TODO:
1. Benchmark saving register speed:
2. Benchmark saving and pruning registers
3. Benchmark the throughput of getting registers while saving and pruning registers

**Comment by j1010001** [comment]
work on splitting this
