### ISSUE TITLE
[Dynamic Protocol State] passing the epoch commitment deadline without an `EpochCommit` event

### ISSUE THREAD

**Issue by AlexHentschel** [onflow/flow-go#5104]
This is a more detailed description of the last `High priority` item in https://github.com/onflow/flow-go/issues/4649:

> - [ ] Take a fresh look at the `InvalidStateTransitionAttempted` and its relation to the node-internal [`EpochEmergencyFallbackTriggered` event](https://github.com/onflow/flow-go/blob/79e079eacf2ca6bc4f04bc455693e9b0ddf5fb7a/state/protocol/events.go#L90-L95) and the [related flag in  `InstanceParams`](https://github.com/onflow/flow-go/blob/79e079eacf2ca6bc4f04bc455693e9b0ddf5fb7a/state/protocol/badger/params.go#L30). See [PR comment here](https://github.com/onflow/flow-go/pull/4868#discussion_r1387423692). In context of this discussion, we will probably also have to consider the option for leaving epoch fallback mode as well. 

## Details

When the `FollowerState` and `ParticipantState` finalize a block, it checks whether the finalization triggers Epoch Fallback mode:
https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/state/protocol/badger/mutator.go#L665-L667
Specifically, the method `epochFallbackTriggeredByFinalizedBlock` checks whether we are passing the epoch commitment deadline without an `EpochCommit` event:
https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/state/protocol/badger/mutator.go#L822-L824
If that is the case, 
 * we [emit an `EpochEmergencyFallbackTriggered` notification](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/state/protocol/badger/mutator.go#L673) 
 * and [set the corresponding data base flag](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/state/protocol/badger/mutator.go#L731-L736)

I find it unintuitive to have two different conditions leading to  an `EpochEmergencyFallbackTriggered`. Technically, the protocol state has already reached an invalid state for a block that has passed the epoch commitment deadline without an `EpochCommit` event being in the fork.

### I would suggest:
* The [check wether the block passed the epoch commitment deadline without an `EpochCommit`](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/state/protocol/badger/mutator.go#L822-L834) could go into the [constructor of the happy-path state machine](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/state/protocol/protocol_state/protocol_statemachine.go#L31)
* In case the check is violated, this block's protocol state would be leaving the happy path. Hence, the constructor would respond with a dedicated sentinel.
* The sentinel is [caught by the Mutator](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/state/protocol/protocol_state/mutator.go#L69) (already in its constructor). 
* Alternatively, we could implement the check entirely in the constructor or the mutator. We would essentially just add another case, where we instantiate an `epochFallbackStateMachine` here: https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/state/protocol/protocol_state/mutator.go#L60-L70 I find this would also be a reasonable approach, because the mutator already [triggers view-based state transitions here](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/state/protocol/protocol_state/mutator.go#L170-L173)

**Comment by jordanschalm** [comment]
Addressed by https://github.com/onflow/flow-go/pull/5108
