### ISSUE TITLE
[Dynamic Protocol State | M2] Sealing Segment Supports Changing ProtocolStateID

### ISSUE THREAD

**Issue by jordanschalm** [onflow/flow-go#5120]
## Context

At the moment, the `SealingSegment` portion of the `Snapshot` API requires that all blocks in the sealing segment must be within the same epoch and epoch phase (see docs [here](https://github.com/onflow/flow-go/blob/a0041b880736789da3303c53c16dcc897794c9a2/engine/access/rpc/backend/backend_network.go#L80-L85)). We have extended this requirement in the Dynamic Protocol state, requiring in general that all blocks in a sealing segment have the same protocol state ID.

Over time we have:
- More potential changes to the protocol state
- More node operators using Dynamic Bootstrap as a general operational tool - not just for staking/unstaking nodes, which is relatively infrequent.

Both of these factors make restrictions on usable snapshots less desirable.

Dynamic Protocol State modifies the block model to create a mapping from block to protocol state, which I am hopeful will make removing this constraint on sealing segments (and root snapshots) easier to implement.

## Proposed Solution
To address this issue, we propose the following changes:

- Introduce a lookup mechanism for mapping protocol state IDs to Rich Protocol State IDs within the sealing segment.
- Modify the sealing segment to accommodate storage for multiple Rich Protocol States, allowing for blocks to reference different protocol state IDs
- Enhance the bootstrapping logic to correctly index the associated protocol state ID for each block within the sealing segment.
- Adjust the bootstrapping logic to support the insertion of multiple Rich Protocol States, facilitating the duplication of specific sub-entities within the Rich Protocol State entry.

### Comments
The `SealingSegment` model is already fairly complicated. Creating the set of protocol states required by a snapshot could be done completely separately, after the sealing segment is built, and stored as a separate field in the snapshot. Conceptually though it is dependent on the sealing segment contents.

**Comment by durkmurder** [comment]
In [PR](https://github.com/onflow/flow-go/pull/5650) for implementing updates to the `Snapshot` API and exposing KV store to the logic outside Dynamic Protocol State I have disabled several tests that depend on functionality described in this issue. Without changes to the `SealingSegment` we cannot support sealing segment where blocks commit to different protocol states, in current implementation such `SealingSegment` will be considered invalid by failing [next check](https://github.com/onflow/flow-go/blob/yurii/5136-querying-kvstore/state/protocol/badger/state.go#L278-L281). 

List of tests that were disabled:
- https://github.com/onflow/flow-go/blob/yurii/5136-querying-kvstore/state/protocol/badger/state_test.go#L317
- https://github.com/onflow/flow-go/blob/yurii/5136-querying-kvstore/state/protocol/badger/state_test.go#L338
- https://github.com/onflow/flow-go/blob/yurii/5136-querying-kvstore/state/protocol/badger/state_test.go#L359
- https://github.com/onflow/flow-go/blob/yurii/5136-querying-kvstore/integration/tests/epochs/cohort1/epoch_join_and_leave_an_test.go#L13
- https://github.com/onflow/flow-go/blob/yurii/5136-querying-kvstore/integration/tests/epochs/cohort1/epoch_join_and_leave_ln_test.go#L13
- https://github.com/onflow/flow-go/blob/yurii/5136-querying-kvstore/integration/tests/epochs/cohort2/epoch_join_and_leave_sn_test.go#L14
- https://github.com/onflow/flow-go/blob/yurii/5136-querying-kvstore/integration/tests/epochs/cohort2/epoch_join_and_leave_vn_test.go#L14

All disabled tests can be found by searching a string: "kvstore: sealing segment doesn't support multiple"

**Comment by jordanschalm** [comment]
Addressed by https://github.com/onflow/flow-go/pull/5656
