### ISSUE TITLE
Change progress loggers to reduce logging overhead

### ISSUE THREAD

**Issue by janezpodhostnik** [onflow/flow-go#5140]
## Problem Definition

This relates to PR https://github.com/onflow/flow-go/pull/5122
To the comments made here https://github.com/onflow/flow-go/pull/5122/files/c26a38eec6564439df9a8934ffff8866f3e3380a#diff-c72a04018fbedd8cfe575b706f0f99a701ce6fea23869a328bbdad4bb8b801ad

The progress log locks on every call which might be expensive

## Proposed Solution

The Progress log should be a Closer and should use channels  to speed it up.

## Definition of Done

- Progress log does not lock on every call

**Comment by j1010001** [comment]
Improvement of checkpointing, migration and node startup performance
