### ISSUE TITLE
Add a transaction ID to `logExecutionIntensities` so its easier to correlate them to the transaction that produce those logs

### ISSUE THREAD

**Issue by janezpodhostnik** [onflow/flow-go#5202]
## Problem Definition

The method `logExecutionIntensities` in transactionInvoker.go does not log which transaction the intensities belong to. This makes it hard use them in certain situations.

see: https://github.com/onflow/flow-emulator/issues/542 and https://github.com/onflow/flow-emulator/pull/543 for more context

## Proposed Solution

Add a transaction ID to those logs

## Definition of Done

- `logExecutionIntensities` also logs transaction ID.

**Comment by j1010001** [comment]
Nice to have for community

**Comment by j1010001** [comment]
@janezpodhostnik to check if this is still needed
