### ISSUE TITLE
[Flow EVM] Empty `ParentBlockHash` for new blocks

### ISSUE THREAD

**Issue by m-Peter** [onflow/flow-go#5219]
## 🐞 Bug Report

While consuming emitted events from Flow EVM interactions, I observed that the `ParentBlockHash` was never set for new blocks. This can also be seen in the relevant function: https://github.com/onflow/flow-go/blob/master/fvm/evm/types/block.go#L49-L54.

![flow-evm-gateway-events](https://github.com/onflow/flow-go/assets/1778965/a2688fe6-c947-4f45-ac17-a618fc616bb4)

In the above screenshot, the payload for `flow.evm.BlockExecuted` events, always has the same value for the `parentHash` key, e.g.:
```bash
parentHash: "0x0000000000000000000000000000000000000000000000000000000000000000"
```

**Comment by ramtinms** [comment]
Just to check, I don't think 5237 is fixing this issue.

**Comment by m-Peter** [comment]
@ramtinms I tried this locally through the EVM Gateway, and it partially fixes the issue:

```shell
flow.evm.BlockExecuted(
    height: 1,
    totalSupply: 7766279631452241920,
    parentHash: "0xe81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421c0",
    receiptRoot: "0x0000000000000000000000000000000000000000000000000000000000000000",
    transactionHashes: ["0xf31ee13dad8f38431fd31278b12be62e6b77e6923f0b7a446eb1affb61f21fc9"]
)

flow.evm.BlockExecuted(
    height: 2, totalSupply: 7766279631452241920,
    parentHash: "0xf31ee13dad8f38431fd31278b12be62e6b77e6923f0b7a446eb1affb61f21fc9",
    receiptRoot: "0x0000000000000000000000000000000000000000000000000000000000000000",
    transactionHashes: ["0xaae4530246e61ae58479824ab0863f99ca50414d27aec0c269ae6a7cfc4c7f5b"]
)
```

The `parentHash` field is being set properly, and I verified this by also using https://github.com/onflow/flow-go/pull/5245 (it points to the correct block hash).

It turns out that it is the `receiptRoot` field which is always being empty. Do we have a way to compute this?
From what I've read, it is related to the `Receipt.PostState` field (https://github.com/ethereum/go-ethereum/blob/master/core/state_processor.go#L118-L129), 
And for the block it should be `DeriveSha(Receipts(receipts))`([source](https://ethereum.stackexchange.com/questions/6537/what-is-the-root-of-a-transaction-receipt)). Currently we have one transaction per block, so basically one receipt as well.

**Comment by sideninja** [comment]
@m-Peter @ramtinms to my understanding we won't have a receipt root available with the current state implementation.
