### ISSUE TITLE
[Flow EVM] Refactor EVM contract for Cadence 1.0

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-go#5350]
The EVM contract, while currently 1.0 compatible, would benefit from leveraging Cadence's updated feature set. Some feedback about access controls using entitlements and `view` modifiers was discussed in https://github.com/onflow/flips/pull/225.

As an example, updating `BridgedAccount.address()` and `.balance()` to be `view` methods will enable inclusion in pre- & post-conditions. Adding an entitlement to privileged `BridgedAccount`/`CadenceOwnedAccount` methods will enable public Capabilities on the base resource.

**Comment by bjartek** [comment]
the contract is located here for clarify 
https://github.com/onflow/flow-go/blob/51202b7a9850a9728576355860b3279bdc1fe5bc/fvm/evm/stdlib/contract.cdc#L4

**Comment by bjartek** [comment]
Should not the implementations here do a pre condition that the internal address is set when trying to for instance send money to it?

**Comment by bjartek** [comment]
What methods is it that needs to be entitled here. I have not follow the FLIP that much but as long as the task is a bit better defined it should be pretty easy.

**Comment by bjartek** [comment]
There is a bit to much knowledge required here for me to do it in EU and I do not have time during US days so I have to pass on this.

**Comment by sisyphusSmiling** [comment]
> Can things that call InternalEVM be view modified?

This is a good point, I would hope this is possible as values like balance & address would be very useful in pre- & post-conditions as well as interface event emissions

**Comment by ramtinms** [comment]
I think it should be possible but I need to sync with the Cadence team to see how to do that.
