### ISSUE TITLE
[Dynamic Protocol State | M2] KV Store upgrade event

### ISSUE THREAD

**Issue by jordanschalm** [onflow/flow-go#5351]
## Context

To avoid relying on sporks to perform updates of KV store it was designed to use HCU-style upgrades. To support such upgrade we need to define VersionUpgrade field in the KV store and use it to coordinate changes between versions.
Node software is operated using specific rules which are called [version requirements](https://www.notion.so/dapperlabs/Protocol-state-key-value-storage-497326ff9cf44ff4a70610a0dad329b3?pvs=4#cbdd2c8308074f9b92bdfd8ee429ec82)

https://github.com/onflow/flow-go/issues/5315 addresses how the version upgrade event is handled within the Protocol State Machine. The event originates as a service event from the smart contract; this issue addresses adding the service event.

## Definition of Done

- Create a new Cadence service event `ProtocolStateVersionUpgrade(newVersion: UInt)`, which accepts a positive integer value representing the new version after the service event is processed
  - I'd suggest putting this event (and other Protocol KV setters) in [FlowServiceAccount](https://github.com/onflow/flow-core-contracts/blob/master/contracts/FlowServiceAccount.cdc)
- Create the `flow-go` model for the event
- Implement conversion (https://github.com/onflow/flow-go/blob/master/model/convert/service_event.go#L20)

**Comment by AlexHentschel** [comment]
In the context of this issue, I feel it is very important to differentiate between the protocol version and the software version. It is a complex, subtle discussion and we need to carefully and unambiguously communicate what we mean.  

Here, we are saying that the software needs to understand a specific protocol version. The Cadence service event specifies the protocol version. Lets be specific in our event:
```
ProtocolStateVersionUpgrade(newProtocolVersion: UInt)
```
