### ISSUE TITLE
[EVM] Add block hash to the logs

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-go#5372]
Logs created by the EVM should contain the block hash as well as the transaction hash: 
https://github.com/onflow/flow-go/blob/b3279863c7787d112128188a243905a43ec1654a/fvm/evm/emulator/emulator.go#L398

The problem is the block is not yet completely formed by the time logs are constructed in the link above. Thus the hash calculation of the block at that time would produce the wrong hash, [as seen here, the procedure is run (where log construction happens)](https://github.com/onflow/flow-go/blob/b3279863c7787d112128188a243905a43ec1654a/fvm/evm/handler/handler.go#L195).
and only [after the direct call hash is added to the block](https://github.com/onflow/flow-go/blob/b3279863c7787d112128188a243905a43ec1654a/fvm/evm/handler/handler.go#L208) which would affect the block hash.

**Comment by ramtinms** [comment]
the block hash is not part of the receipt calculation, so the block hash won't be an issue, though txHash is.
