### ISSUE TITLE
Compress data stored in badgerDB

### ISSUE THREAD

**Issue by zhangchiqing** [onflow/flow-go#5402]
Inspecting the protocol data stored in badgerDB, I saw lots of data stored in clear text. Will try again to see if possible the data can be compressed.

**Comment by j1010001** [comment]
Thought this is low-hanging fruit, but need to revisit the effort.

**Comment by zhangchiqing** [comment]
Experimented with https://github.com/onflow/flow-go/pull/5496

Close in favor of https://github.com/onflow/flow-go/issues/6137
