### ISSUE TITLE
Commit emulated migration results

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-go#5410]
## Problem Definition

Leading up to the network HCU at the Cadence 1.0 milestone, developers will stage their contract contract code with expectations that regularly scheduled migration will be emulated on all staged contracts. Guidance will advise developers to stay up to date on their contracts' validation status, making communication a critical component of the validation process.

## Proposed Solution

The current [staging contract](https://github.com/onflow/contract-updater) enables [commitment of validation results](https://github.com/onflow/contract-updater/blob/main/transactions/migration-contract-staging/admin/commit_migration_results.cdc) in addition to [querying contract status against those results](https://github.com/onflow/contract-updater/blob/main/scripts/migration-contract-staging/is_validated.cdc).

In order for this functionality to be useful, the validation mechanism should commit the results of the emulated migration to the contract with the snapshot timestamp of the state used for validation.

While validation results can be communicated via a central dashboard, commiting results onchain enables ecosystem platforms - Flowdiver, ContractBrowser, Flowview, etc - to display the validation status of a given contract without the need to standup an API. This gives us broader distribution to meet developers where they are as well as consistent messaging about the state we want all contracts to achieve - not just staged, but staged & validated.

## Definition of Done

Results of validation containing snapshot timestamp and array contract identifiers that failed validation is committed via [transaction](https://github.com/onflow/contract-updater/blob/main/transactions/migration-contract-staging/admin/commit_migration_results.cdc) by either the staging contract host or another account configured with `MigrationContractStaging.Admin` Capability.

**Comment by turbolent** [comment]
@j1010001 Can you please add this to the "upgrade" milestone?
