### ISSUE TITLE
[AN] Event streaming special value for height

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-go#5481]
Currently when subscribing to events if you provide a value of 0 as the start height that value is treated as latest height. This can be very confusing and lead to bugs since height 0 would probably often be confused as the first height on the network. 
The consequence this can have in services that monitor network is they mistakenly use 0 as first but miss a lot of events (trust me, I've burned myself like that).
My suggestion is for special values used for heights to be set as maximum number of the type and then decreased by one for each new value: `Max(UInt64)-X`.

**Comment by peterargue** [comment]
@sideninja do we still need this issue now that we've added the new endpoints?
