### ISSUE TITLE
[Flow EVM] EVM block overhead optimization

### ISSUE THREAD

**Issue by ramtinms** [onflow/flow-go#5504]
We could optimize the EVM block overhead in multiple ways. for example: 
- instead of calling random for each block we might do it on demand
- minimizing the data on events (e.g. duplicated tx hash block hash, block index)

**Comment by sideninja** [comment]
> instead of calling random for each block we might do it on demand

@ramtinms with the get random source arch implementation do we still even need the random call?

**Comment by ramtinms** [comment]
I think we still want to keep it given legacy EVM contracts might rely on it for some operations

**Comment by sideninja** [comment]
Revisit event fields if some can be removed
