### ISSUE TITLE
[EFM] Epoch recovery data generation

### ISSUE THREAD

**Issue by kc1116** [onflow/flow-go#5637]
## Context
EFM can be exited only by a special service event, **_EpochRecover_**, which initially originates from a manual service account transaction. The full epoch data must be generated manually and submitted with this transaction in order for an  
**_EpochRecover_** event to be emitted. Generate all data needed for the recovery transaction.

## Definition of Done
Generate new cluster assignments.
- [x] Retrieve identity table from the protocol state snapshot of the current epoch (being extended through EMF) (.Identities). Take the node IDs from this list to generate nodeIDs.
- [x] Compute a cluster assignment using the identity table from above. We can reuse sporking utility logic. 
- [x] Using the `RecoveryEpoch` epoch counter, and the cluster assignment from above, generate the cluster root blocks for the `RecoveryEpoch`. Then generate the cluster QCs. (**Note:** we can re-use the sporking utility logic here; this also requires that DLI+FF control a supermajority of collection node staking keys.)
- [x] Retrieve DKG key vector from the protocol state snapshot of the last successful epoch (`.Epochs.Current.DKG`). 

## Further reading:

https://www.notion.so/dapperlabs/Spork-less-Epoch-Fallback-Recovery-Design-II-Epoch-Extensions-a7673e45e9064d12b6b48aa517bd1763?pvs=4#e56ea67b97bc4d19b80be0d18a68a806

**Comment by franklywatson** [comment]
Linking PR

**Comment by franklywatson** [comment]
Didn't work
