### ISSUE TITLE
[EFM] Add EpochExtension to Epoch Data Model 

### ISSUE THREAD

**Issue by kc1116** [onflow/flow-go#5717]
# Context 
An EpochExtension is an addition to the current epoch data model, which allows the final view of the epoch to be increased one or more times. These EpochExtension's are added to the current epoch when the state encounters EFM.

# Definition of Done

- [ ] Update the Epoch data model to support EpochExtensions
- [ ] Track epoch extensions in the ProtocolStateMachine

# Further reading 

[Design](https://www.notion.so/dapperlabs/Spork-less-Epoch-Fallback-Recovery-Design-II-Epoch-Extensions-a7673e45e9064d12b6b48aa517bd1763?pvs=4#b0f110f8a6c64b8999aa64b7197ab3ec)

**Comment by durkmurder** [comment]
Implemented in https://github.com/onflow/flow-go/pull/5773
