### ISSUE TITLE
[EFM] Dynamic Protocol State injects EpochExtension when entering EFM

### ISSUE THREAD

**Issue by kc1116** [onflow/flow-go#5724]
# Context
The Dynamic Protocol State already detects and triggers EFM. It will also need to inject `EpochExtension`s when EFM is triggered, and on an ongoing basis while EFM remains triggered. When we enter EFM as a result of processing some block **_B_**, we switch to using the epochFallbackStateMachine to process subsequent blocks. Modify existing EFM triggering logic to simultaneously inject the first EpochExtension to the protocol state in block **_B_**. 

This issue is for injecting the first `EpochExtension` (entering EFM). https://github.com/onflow/flow-go/issues/5726 is for adding `EpochExtension`s on an ongoing basis (maintaining EFM). https://github.com/onflow/flow-go/issues/5731 is for the detailed logic to avoid changing already committed leader selections.

# Further Reading 
[Design](https://www.notion.so/dapperlabs/Spork-less-Epoch-Fallback-Recovery-Design-II-Epoch-Extensions-a7673e45e9064d12b6b48aa517bd1763?pvs=4#14d3e9548f634c1d91cac856cb1b21af)

**Comment by durkmurder** [comment]
Implemented in https://github.com/onflow/flow-go/pull/5773
