### ISSUE TITLE
[EFM] Dynamic Protocol State maintains EFM by injecting EpochExtensions

### ISSUE THREAD

**Issue by kc1116** [onflow/flow-go#5726]
# Context 

After an initial EpochExtension is added Subsequent `EpochExtension`s are added to the Protocol State according to the following algorithm:

Suppose we are in EFM and are processing block **_B_**. 

- Let $\hat{V}$ be the final view of the current epoch, taking into account prior `EpochExtension`s.

We will add a new `EpochExtension` to the protocol state in block **_B_**  iff both are true:
<img width="648" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVIwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--401a752051a09a5db5e976862a25456a9e3046d5/Screenshot%202024-04-18%20at%202.10.13%E2%80%AFPM.png" alt="Screenshot 2024-04-18 at 2.10.13 PM.png" />

If we add a new EpochExtension, it will have the following form:

<img width="654" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVowQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4732135056fa15d63519009129b4bede7faf2b52/Screenshot%202024-04-18%20at%202.10.35%E2%80%AFPM.png" alt="Screenshot 2024-04-18 at 2.10.35 PM.png" />

This issue is for adding `EpochExtension`s on an ongoing basis (maintaining EFM). https://github.com/onflow/flow-go/issues/5724 is for injecting the first `EpochExtension` (entering EFM).

# Definition of Done 
Update Dynamic Protocol State Mutator to maintain EFM by periodically adding new EpochExtensions.

# Further Reading 
[Design](https://www.notion.so/dapperlabs/Spork-less-Epoch-Fallback-Recovery-Design-II-Epoch-Extensions-a7673e45e9064d12b6b48aa517bd1763?pvs=4#87c69537e9e74b5b9be6ca0dbed5bc1e)

**Comment by AlexHentschel** [comment]
see https://github.com/onflow/flow-go/issues/5631 for more details

related issues:
* https://github.com/onflow/flow-go/issues/5724 is for injecting the first `EpochExtension` (entering EFM). 
* https://github.com/onflow/flow-go/issues/5726 is for adding `EpochExtension`s on an ongoing basis (maintaining EFM).
* https://github.com/onflow/flow-go/issues/5731 is for the detailed logic to avoid changing already committed leader selections.

**Comment by durkmurder** [comment]
Remaining logic implemented in https://github.com/onflow/flow-go/pull/5898
