### ISSUE TITLE
[EFM] Modify EFM logic do not enter EFM while in EpochCommitted phase

### ISSUE THREAD

**Issue by kc1116** [onflow/flow-go#5731]
# Context 
When entering EFM currently we will discard any partial data for a committed Epoch, we instead need to go through the committed epoch and enter EFM by adding an extension to the committed epoch.  Modify EFM logic in the Protocol State Machine: do not enter EFM while in phase EpochCommitted. 

# Open Questions
It's an open question whether we should do this at all. See https://www.notion.so/flowfoundation/Spork-less-Epoch-Fallback-Recovery-Design-II-Epoch-Extensions-e923ca84b4d848c5a17de4b18fb5afd5?pvs=4#a5d27c278ec249cbb93784cedb7e7ec3

**Comment by AlexHentschel** [comment]
see https://github.com/onflow/flow-go/issues/5631 for more details

related issues:
* https://github.com/onflow/flow-go/issues/5724 is for injecting the first `EpochExtension` (entering EFM). 
* https://github.com/onflow/flow-go/issues/5726 is for adding `EpochExtension`s on an ongoing basis (maintaining EFM).
* https://github.com/onflow/flow-go/issues/5731 is for the detailed logic to avoid changing already committed leader selections.

**Comment by jordanschalm** [comment]
Hey @durkmurder I think we can close this, right?

**Comment by jordanschalm** [comment]
Closing as completed
