### ISSUE TITLE
[Access] Resource contention from local data lookups

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-go#5747]
## Problem Definition

Recently the public nodes encountered high response time. This started after rolling out support for using local data for transaction results. At its worst, the average response time for impacted nodes was around 1 seconds. This is about a 20x increase from normal behavior.

Additionally, we observed that writes to the db were also slow. Some nodes fell several hundred blocks behind indexing collections.  Collections are relatively large data structures and involve multiple writes per transaction.

Here's a CPU profile from one of the nodes at the time, zooming into the API traces:
<img width="2967" alt="image" src="https://github.com/onflow/flow-go/assets/89119817/10f9b942-94aa-40f5-a4a9-1551c4180341">

Most notable is that all of the endpoints spend a majority of CPU time in `runtime.asyncPreempt` within badgerDB seeks. `runtime.asyncPreempt` indicates that a goroutine was forcibly preempted during execution, typically during long running loops that never release their context. In our case, they were converting blobs of data from the db from bytes to `uint32` during seek. 

Some observations
* Large numbers of concurrent reads/writes to the db is causing general slow responses for all queries
* Most of the slowness is from database reads (seeks)
* Events for a block are looked up for both event and tx result queries, so caching could make a significant difference

Needs further investigation:
* Is gc causing/making this worse?
* What do the mutex/block traces look like?

## Takeaways

The new local data features makes resource contention more likely, especially on high throughput nodes like the public endpoints.

Experiment with the following:

- [x] Spread the request volume across a larger number of nodes. The reduced requests per node should reduce the contention
- [x] #5754
- [ ] Investigate caching in the tx results endpoint
- [ ] Investigate go GC tuning for ANs
- [ ] Look into disk configurations and options to use lower latency drives
- [ ] Increase the number of CPU cores per VM

**Comment by bluesign** [comment]
I remember commenting on this ( or creating an issue ) but somehow couldn't find now. 

Here is what I remember maybe it helps. There is a cache on storage layer and it is for 1000 blocks currently, and it is LRU cache. What happens is when someone is requesting old height range ( someone is indexing old blocks etc, and they request max amount of blocks (250 iirc) )  they are evicting recent blocks from cache. This may be causing recent requests to go to badger instead of cache.

**Comment by peterargue** [comment]
> I remember commenting on this ( or creating an issue ) but somehow couldn't find now. (edit: found #961 )
> 
> Here is what I remember maybe it helps. There is a cache on storage layer and it is for 1000 blocks currently, and it is LRU cache. What happens is when someone is requesting old height range ( someone is indexing old blocks etc, and they request max amount of blocks (250 iirc) ) they are evicting recent blocks from cache. This may be causing recent requests to go to badger instead of cache.

yea, that's very likely causing issues here. I think a solution like `withNoCacheOnRetrieve` could be helpful. I'll do some experimentation.

**Comment by peterargue** [comment]
Another interesting section from a CPU profile:
<img width="2883" alt="image" src="https://github.com/onflow/flow-go/assets/89119817/52102e19-6bce-42fe-9ce4-01bd6da26d6f">


This is showing bitswap using 18% of the node's CPU calculating the size of blobs. It's possible to add a cache for bitswap blobs, which should reduce the db lookups needed for this operation.

**Comment by peterargue** [comment]
Profiles from one of the ANs experiencing slow response times:

CPU:
<img width="2880" alt="image" src="https://github.com/onflow/flow-go/assets/89119817/cbd4c407-633a-4d14-ab5d-e912b1f97961">

Note:
* 17% of CPU is used by bitswap looking up the size of recent data blobs
* 10% is used for DHT related activities
* 14% is used by go garbage collection (this varies over time)
* 30% is used by the APIs (including profiling)


Alloc Space:
<img width="2884" alt="image" src="https://github.com/onflow/flow-go/assets/89119817/17abac64-3884-4e02-9066-30377186c14d">

Note:
* 52% of allocations are from syncing execution data (this is typical)
* 14% is from DHT operations
* 18% is from API requests (including profiling)


Inuse Space:
<img width="2886" alt="image" src="https://github.com/onflow/flow-go/assets/89119817/c89020a5-3bf0-423e-bde4-0364bb572f6c">

Note: 
* 50% of memory is used by badger for the L0 cache
* 30% is used by badger for compaction
* 6% is used by the DHT to store the provider map
* Less than 5% is used by the APIs (including profiling)


### Observations

The 17% cpu used by bitswap looking up the size of recent data blobs van be eliminated by enabling a cache on the blobstore.

10% of CPU for DHT operations and some amount of the garbage collection needed to free DHT allocations could be eliminated by disabling the DHT.

**Comment by peterargue** [comment]
Here's an execution trace from a node experiencing slow response times:
<img width="2207" alt="image" src="https://github.com/onflow/flow-go/assets/89119817/cac3e771-e6eb-4480-851f-8c0eb0bdfff6">

Note: while there are large blocks of time where a majority of the available cores are used by long running tasks, there are always several available codes, and many that are relatively underutilized.

**Comment by peterargue** [comment]
I attempted to reproduce this on testnet pushing one AN to 87% CPU utilization with:
* 1000 request per second across calls to get blocks, events, txresults and accounts.
* 200 execution data streams

During this test p90 grpc response time increased from 6ms to 30ms and rest response time 5ms to 25ms. Response times did not run away to hundreds of milliseconds.

I also monitored profiles, and didn't see `runtime.asyncPreempt` show up on any of the API cpu samples.

**Comment by peterargue** [comment]
We disabled the DHT on several nodes, but were never able to reproduce this issue on the flow foundation ANs. After migrating to new infra, profiles from the QN nodes also stopped showing the contention. I'm going to close this out for now, but may reopen if it comes up again
