### ISSUE TITLE
[EVM] Using hex-encoded address as event values

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-go#5911]
EVM events `CadenceOwnedAccountCreated` `FLOWTokensDeposited` `FLOWTokensWithdrawn` contain the EVM address as byte array, this is not great for human-readability and has been suggested we could change to hex-encoded addresses. 

The original discussion:
https://discord.com/channels/613813861610684416/1239301250630291517

**Comment by sideninja** [comment]
@ramtinms @m-Peter 
Do you see any issues or reservations if we change this?

cc @bjartek @sisyphusSmiling @bluesign

**Comment by sisyphusSmiling** [comment]
I don't anticipate issues from my perspective. Human-readable events are definitely preferred, and the emitted string values can soon be deserialized into `EVMAddress` objects with #5892. At this stage, are there any consumers that would be impacted by the event change - gateway, wallets, etc.?

**Comment by ramtinms** [comment]
Yeah, I like changing it to hex

**Comment by m-Peter** [comment]
Fine by me as well. This is already the case for the `EVM.TransactionExecuted` event:

```cadence
access(all)
event TransactionExecuted(
    ...
    // if transaction was a deployment contains a newly deployed contract address
    contractAddress: String,
    ...
)
```
