### ISSUE TITLE
[EVM] Support for transactions debug

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-go#5952]
To support transaction execution tracing and the debug_traceTransaction API on the EVM Gateway we must produce tracing of transaction execution. This can be done by configuring [EVM with a tracer](https://github.com/ethereum/go-ethereum/blob/fa6107c85e5717f10b2a57d470ead0e34b2152ba/core/vm/interpreter.go#L28) which is an implementation [of the `EVMLogger`](https://github.com/ethereum/go-ethereum/blob/1f35988a0047b5430eb074f0f43e6d0466c468a9/core/vm/logger.go#L30). 

There are a couple of design decisions on how to implement the above requirement. We will cover two ways of achieving the goal, one is a shorter-term solution, and one a longer-term (better) solution.

**Shorter-term solution**

We configure EVM on the execution node with tracing capabilities to produce the outputs we need to index on EVM Gateway. This can be done on a single execution node since that will probably slow down the node to a certain degree. Then the next step is to share this data to the EVM Gateway which will index it. There are couple of options here:
- first is to use bitswap, while probably best option long-term, it introduces more complexity and since this is a short-term solution it doesn't prove itself worth it, 
- the second option is to create a gRPC API endpoint on the execution node to fetch the traces for a transaction, this requires running a new API and storing data for traces produced locally, which likely can be done in memory. This will to some extent increase the memory usage on the execution node, depending on how much history we decide to keep, but also adds some complexity to prune the data, and exposes an API of the execution node to the outside world. 
- the third option is to use an upload service for execution node to upload the data and then EVM GW have a place to download it. A service like GCP can be used. The risks of this options are failure with uploads. 

**Longer-term solution**

A better longer-term solution is to produce the traces locally on EVM gateway thus not adding complexity and resource-requirements to the execution node. This could be done by running an emulator on EVM gateway configured in a way that it simulates network execution using APIs on AN to obtain register values. This way we can simulate transaction execution against any network locally and produce the output. This option I believe would be best because it doesn't add complexity on EVM GW.

Some of the issues to address
- direct call "deploy at" function doesn't allow currently to produce traces
- TBD

The relevant issue on the EVM Gateway: https://github.com/onflow/flow-evm-gateway/issues/251

**Comment by SeanRobb** [comment]
GM!

Checking in here is there an ETA for this endpoint on the Gateway to be resolved?

Assuming both the short and long term solutions would have the endpoint functional on the gateway.

**Comment by sideninja** [comment]
ETA for this on GW is next week (hopefully first half)
