### ISSUE TITLE
Include EVM in core contract migration

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-go#5958]
## Problem Definition

The EVM contract does not seem to be included in the core contracts migration currently in use on Testnet. This is evident in the May 15th [migration failure of the `FlowEVMBridgeHandletInterfaces` contract](https://github.com/onflow/cadence/blob/master/migrations_data/staged-contracts-report-2024-05-15T10-00-00Z-testnet.md?plain=1#L110) which is staged with a dependency on EVM in its 1.0 version.

## Proposed Solution

Include the 1.0 version of the EVM contract along with other core contracts in network migrations.

## Definition of Done

Contracts with 1.0 dependencies on EVM can be successfully migrated from code as staged.

**Comment by turbolent** [comment]
The contract is staged, but the staged version does not check, see https://github.com/onflow/cadence/blob/master/migrations_data/staged-contracts-report-2024-05-15T10-00-00Z-testnet.md?plain=1#L14

**Comment by sisyphusSmiling** [comment]
Ah I see what you're saying now @turbolent. So it's not that the contract needs to be included with core contracts migration but needs to be corrected so it can migrate successfully, yeah?

**Comment by turbolent** [comment]
I'm a bit confused about this. The report says `v0.35.7-crescendo-preview.23-atree-inlining` was used, and the report says the error in the `EVM` contract is on line 300:
```
error: mismatched types
   --> 8c5303eaa26202d6.EVM:300:37
    |
300 |             return EVMAddress(bytes: addressBytes)
    |                                      ^^^^^^^^^^^^ expected `[UInt8; 20]`, got `AnyStruct`
```

But looking at the code, that line does not exist:
https://github.com/onflow/flow-go/blob/v0.35.7-crescendo-preview.23-atree-inlining/fvm/evm/stdlib/contract.cdc#L300

**Comment by turbolent** [comment]
@onflow/flow-cadence-execution

**Comment by bluesign** [comment]
line 300 on staged contract 

https://f.dnz.dev/0x2ceae959ed1a7e7a/0x8c5303eaa26202d6_EVM

**Comment by turbolent** [comment]
Oh, thanks @bluesign! 

Somehow this got staged? I was under the impression that we would stage it like the other core contracts.
I recently updated the migration to do that: https://github.com/onflow/flow-go/pull/5915

I'd recommend we update it without staging, because then we always get the most recent version of the contract staged, i.e. what is in the flow-go codebase. This avoids mistakes like this one, where what is in the codebase and what is staged do not match.

**Comment by turbolent** [comment]
@sisyphusSmiling Can you confirm based on the latest migration report and close if complete?

**Comment by turbolent** [comment]
[`0xdfc20aee650fcbdf` `FlowEVMBridgeHandlerInterfaces` succeeded now](https://github.com/onflow/cadence/blob/master/migrations_data/staged-contracts-report-2024-06-05T10-00-00Z-testnet.md?plain=1#L343), closing
