### ISSUE TITLE
Include `NFTStorefrontV2` in the testnet migrations

### ISSUE THREAD

**Issue by joshuahannan** [onflow/flow-go#5963]
### Issue to be solved

The `NFTStorefrontV2` needs to be migrated on testnet, but the testnet key is missing. We need to include it in the same migrations as all the core contracts, since we do not have a way to stage it normally.

Projects on testnet and migrationnet use this contract as a dependency, so not having the migrated version will block them from migrating and testing properly

### Suggested Solution

* Use `NFTStorefrontV2` version from this branch: https://github.com/onflow/nft-storefront/blob/stable-cadence-refactor/contracts/NFTStorefrontV2.cdc
* Migrate `NFTStorefrontV2` after all the other core contracts have been migrated but before regular staged contracts are migrated

**Comment by turbolent** [comment]
@joshuahannan opened https://github.com/onflow/flow-go/pull/5964, PTAL 🙏

**Comment by joshuahannan** [comment]
yes, that is the correct address for `NFTStorefrontV2`. 👍

**Comment by turbolent** [comment]
@joshuahannan Sounds good! The PR is now merged, let's see if it works in the next trial migration of TN

**Comment by j1010001** [comment]
it worked: https://github.com/onflow/cadence/blob/master/migrations_data/staged-contracts-report-2024-05-29T10-00-00Z-testnet.md
