### ISSUE TITLE
[EFM | M3] Event emission and metrics on finalization 

### ISSUE THREAD

**Issue by AlexHentschel** [onflow/flow-go#6013]
Upon finalization of block, we emit node-internal notifications and metrics (see `mutators` aka [`FollowerState` and `ParticipantState`](https://github.com/onflow/flow-go/blob/5c197b4bb6185c23f4e62979271615d524ede941/state/protocol/badger/mutator.go#L673)). 

### ToDo

This needs to be updated to the new EFM logic, as the existing logic does not understand recovering from EFM (outside of sporks). In particular, the [`FollowerState` and `ParticipantState`](https://github.com/onflow/flow-go/blob/5c197b4bb6185c23f4e62979271615d524ede941/state/protocol/badger/mutator.go#L673) need to support:
* entering EFM (finalization of block that changes  `InvalidEpochTransitionAttempted` from `false` -> `true`)
* additions of epoch extensions (👉 https://github.com/onflow/flow-go/issues/5723)
* recovery epoch committed (finalization of block that changes `InvalidEpochTransitionAttempted` from `true` -> `false`)
* recovery epoch entered (epoch transition)

**Comment by AlexHentschel** [comment]
might have some overlap with https://github.com/onflow/flow-go/issues/5723

**Comment by AlexHentschel** [comment]
List of places in the code that need updating
* `FollowerState` on l block finalization:
  https://github.com/onflow/flow-go/blob/5c197b4bb6185c23f4e62979271615d524ede941/state/protocol/badger/mutator.go#L699-L701


Caution: This list is likely not exhaustive! Be on the lookout for additional spots in the codebase.

**Comment by jordanschalm** [comment]
Closed by https://github.com/onflow/flow-go/pull/6062
