### ISSUE TITLE
coaOwnershipProofValidator should not fail on backend error

### ISSUE THREAD

**Issue by bluesign** [onflow/flow-go#6021]
## 🐞 Bug Report

currently when for example wrong address is provided in the proof, coaOwnershipProofValidator panics, it should not panic, otherwise this would be a free DoS on evm transactions and coinbase. 

## Reproduction steps

1. send a proof with non-existing address 

## Expected behaviour

proof should return false. 

## Additional context

currently panics like this: 

```
   Received unexpected error:
                            [Error Code: 1101] error caused by: 1 error occurred:
                                * [Error Code: 1101] cadence runtime error: Execution failed:
                             --> 792565a37fccd2cd352bb3d7e483d6aeac5e68263e7059874aa18534fb8ef0f0:7:16
                              |
                            7 |                         let res = EVM.run(tx: tx, coinbase: coinbase)
                              |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

                            error: unexpectedly found nil while forcing an Optional value
                               --> f8d6e0586b0a20c7.EVM:612:22
                                |
                            612 |             let key = acc.keys.get(keyIndex: signature.keyIndex)!
                                |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ramtinms** [comment]
Backend errors (despite their names) are not fatal errors, they only capture errors that are rooted from the FVM env and would be gracefully handled (fails the outer layer flow transaction). So there is no risk in terms of Dos.

Though I've updated the code at #6025, so it would be more helpful for users to understand the issue.

**Comment by bluesign** [comment]
Thank @ramtinms, just to explain how I see this as a potential attack ( maybe DoS term was a bit lax in this context ) , EVM transaction failing the outer cadence transaction in my opinion is risky; 

I think there are 2 issues with this: 

- If I am running a gateway service; economical transaction incentives and competitive fees market will lead me to run transactions via BatchRun. This means any transaction failing the cadence transaction, will leave me in a state that, I have to run all individually (for a loss) or fail them all somehow. 

- again if I am running a transaction for others, even if I am running transaction for someone else, this will be net negative, as I will have zero revenue as coinbase, but will pay the flow transaction fee. 

I think it will be useful to provide some guarantees in this area.

**Comment by sideninja** [comment]
> This means any transaction failing the cadence transaction, will leave me in a state that, I have to run all individually (for a loss) or fail them all somehow.

If one of the transaction in a batch fails, others should be still executed normally.

**Comment by sideninja** [comment]
> again if I am running a transaction for others, even if I am running transaction for someone else, this will be net negative, as I will have zero revenue as coinbase, but will pay the flow transaction fee.

If the transaction fails it will still consume the gas up to that point which would be paid to the coinbase.

**Comment by bluesign** [comment]
@sideninja yeah those 2 are the points I am trying to make here actually. Failing outer layer was failing those guarantees.
