### ISSUE TITLE
SystemContractsForChain missing some contracts

### ISSUE THREAD

**Issue by bluesign** [onflow/flow-go#6142]
## 🐞 Bug Report

it is missing some contracts like FungibleTokenMetadataViews, FungibleTokenSwitchboard etc.

**Comment by joshuahannan** [comment]
Can you link to what you are referring to? Those contracts are deployed as part of bootstrapping right now

**Comment by bluesign** [comment]
here @joshuahannan : https://github.com/onflow/flow-go/blob/ac52b6d9cb75fcc4fc8a26d017a11c28f22f6351/fvm/systemcontracts/system_contracts.go#L187-L210
