### ISSUE TITLE
[EVM] Random source with 32 bytes

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-go#6165]
The get random source function on the Cadence arch now returns an uint64 (8 bytes), which is not ideal. We should return all the data we get from the random beacon which 32 bytes.

**Comment by turbolent** [comment]
Just curious: Why is it not ideal?

**Comment by sideninja** [comment]
@turbolent this is the thread where we discussed it: https://discord.com/channels/613813861610684416/1167476806333513800/1255560444425277481

**Comment by turbolent** [comment]
@sideninja Thank you!
