### ISSUE TITLE
[Flow EVM] Populate fields for EVM `GenesisBlock`

### ISSUE THREAD

**Issue by m-Peter** [onflow/flow-go#6282]
Currently, there are a few fields missing for the EVM [GenesisBlock](https://github.com/onflow/flow-go/blob/f296f51d7ecf77692e8daa3cb45a86deeae8cbe3/fvm/evm/types/block.go#L90-L98), such as:
- `TotalGasUsed`
- `Timestamp`
- `TransactionsHashRoot`

**Side Note:** Given that this is a block which JSON-RPC operators need to provide, would it be worthwhile to emit a `EVM.BlockExecuted` event for it?
One way to do this, could be when the `EVM` contract is first deployed to a Flow Network (e.g. previewnet / testnet / mainnet etc).

**Comment by ramtinms** [comment]
good call out, I'll create a PR to populate those fields so we won't have this problem on Testnet. Genesis is stored the very first time the network is launched.

**Comment by m-Peter** [comment]
> Genesis is stored the very first time the network is launched.

Is it stored in the StateDB? If so, how can a 3rd party tool access it, for example, the EVM Gateway? :thinking: I guess we can use the local State Index there.

**Comment by ramtinms** [comment]
Its not stored on the StateDB, but we probably should emit an event for it?

**Comment by m-Peter** [comment]
The event emission sounds like a good idea :+1:

**Comment by ramtinms** [comment]
this should address the issue https://github.com/onflow/flow-go/pull/6325 
I also made genesis block chain dependent so the hash would be different

**Comment by ramtinms** [comment]
I updated the genesis with the info but decided to not emit the event to not break the assumption of at most single EVM block per Flow block.

**Comment by m-Peter** [comment]
Very good point :+1: It didn't occur to me before.
