### ISSUE TITLE
Add a Time To Seal metric to access node to track time it takes to seal a transaction

### ISSUE THREAD

**Issue by vishalchangrani** [onflow/flow-go#6448]
## Problem Definition

What problem is this solving?

Currently, there are Access node metrics to track [Time To Finalization (TTF)](https://github.com/onflow/flow-go/blob/9102a5a6d8e19ab3cb2f84deb78f9fed657d6780/module/metrics/transaction.go#L52) and [Time To Execute (TTE)](https://github.com/onflow/flow-go/blob/9102a5a6d8e19ab3cb2f84deb78f9fed657d6780/module/metrics/transaction.go#L66) for a transaction.
However, we are missing the metric to track Time To Seal (TTS) for a transaction.

## Proposed Solution

What are the proposed solutions to this problem?

Add a new metric that tracks TTS.

## Definition of Done

What tests must pass for this issue to be considered solved?

The TTS metric is available and there is an internal Grafana panel that shows this metric.

**Comment by peterargue** [comment]
@vishalchangrani how urgent is this?

**Comment by franklywatson** [comment]
It's already in progress and under review. Hopefully be done soon

**Comment by vishalchangrani** [comment]
> [@vishalchangrani](https://github.com/vishalchangrani) Should this one be backported to the `v0.37` release?

yes, please can you back port? The next network upgrade is still far far away and it will help to have this metric live
