### ISSUE TITLE
Define Internal Partners set in the root block finalization for validation

### ISSUE THREAD

**Issue by zhangchiqing** [onflow/flow-go#6483]
## Context 

[Addressing review comments](https://github.com/onflow/flow-go/pull/6472#pullrequestreview-2314128301)

[The root block creation bootstrap command](https://github.com/onflow/flow-go/blob/master/cmd/bootstrap/cmd/rootblock.go#L173) uses information from both internal nodes and partner nodes to create the root block. Internal node information is retrieved locally, while partner node information is obtained from the identity table state.

During a spork, data from some partners (Dapper nodes) are treated as internal nodes for root block creation. This results in an overlap between internal and partner nodes, causing incorrect calculations for the percentage of partner collection nodes and leading to validation failures.

We addressed this by[ identifying the overlap between internal and partner nodes](https://github.com/onflow/flow-go/blob/master/cmd/bootstrap/cmd/rootblock.go#L173), treating the overlapping nodes as internal nodes.

However, this approach automatically accepts the overlap without review or validation, introducing potential risks.

A better solution would be to specify the list of internal partners in a file, using it to validate the overlap between internal and partner nodes. Overlaps should only be accepted if they match the specified list, with exceptions thrown for mismatches.

This approach not only provides a clearer definition of internal partners in the code but also helps prevent errors.

**Comment by JHON12091986** [comment]
I would like to work on this issue. Please assign it to me.

Thank you for your time.
