### ISSUE TITLE
[Access] Implement web socket connection mock for unit testing of web socket controller

### ISSUE THREAD

**Issue by Guitarheroua** [onflow/flow-go#6635]

**Comment by illia-malachyn** [comment]
The `WebsocketController` accepts a WebSocket (`ws`) connection as an argument. To effectively unit test this, we need to mock the WebSocket connection. However, the Gorilla WebSocket library's connection interface is extensive and challenging to mock directly. To simplify testing, we can create a wrapper interface around the Gorilla WebSocket connection. This wrapper will be easier to mock, allowing us to simulate the WebSocket's behavior with custom channels that facilitate reading and writing data.

The wrapper interface, `WebsocketConnection`, defines the core methods for testing: `ReadJSON`, `WriteJSON`, and `Close`. Using this interface, we can verify that our controller sends and receives the expected data and behaves as intended. 

The code outline below shows how this can be implemented:

```go
type WebsocketConnection interface {
    ReadJSON(v interface{}) error
    WriteJSON(v interface{}) error
    Close() error
}

type GorillaWebsocketConnection struct {
    conn *websocket.Conn
}

func NewGorillaWebsocketConnection(conn *websocket.Conn) *GorillaWebsocketConnection {
    return &GorillaWebsocketConnection{
        conn: conn,
    }
}

// Ensures that GorillaWebsocketConnection satisfies the WebsocketConnection interface
var _ WebsocketConnection = (*GorillaWebsocketConnection)(nil)
```

In our test setup, a handler can initialize a new WebSocket connection using `NewGorillaWebsocketConnection` and pass it to the controller:

```go
newConn := NewGorillaWebsocketConnection(conn)
controller := NewWebSocketController(logger, h.websocketConfig, h.streamApi, h.streamConfig, newConn)
controller.HandleConnection(context.TODO())
```

To facilitate testing, a mock struct, `WebsocketConnectionMock`, is defined. This mock struct includes custom channels (e.g., `socket` and `testSocket`) for simulating the connection behavior, as well as a `closed` state to indicate if the connection has been terminated. 

```go
type WebsocketConnectionMock struct {
    mock.Mock
    socket     chan interface{}
    closed     bool
}
```

By using this setup, we can easily simulate data exchange through the mock channels and test that `WebsocketController` performs as expected.

**Comment by illia-malachyn** [comment]
This should be a P0
