### ISSUE TITLE
[Access] Add client id for subscriptions

### ISSUE THREAD

**Issue by Guitarheroua** [onflow/flow-go#6637]
This should be discussed with the FCL team due to the comment: https://github.com/onflow/flow-go/pull/6630#discussion_r1835495225

**Update after meeting:**  

1. For all actions ("subscribe," "unsubscribe," "listOfSubscriptions"), the client will generate and pass a unique correlation UUID as an argument.  
2. The backend will receive and store the correlation UUID until the action is completed.  
3. After an action is completed (successfully or unsuccessfully), the response sent back to the client should include the unique correlation UUID provided by the client in request to the WebSocket controller.

**Comment by bluesign** [comment]
Another option is to embed request into response ( SubscribeMessageResponse will contain SubscribeMessageRequest )
