### ISSUE TITLE
[Flow EVM] Investigate the wrong values returned by `blockhash`

### ISSUE THREAD

**Issue by m-Peter** [onflow/flow-go#6715]
This was reported in https://github.com/onflow/flow-go/issues/6552#issuecomment-2466610430

cc @bluesign @j1010001 I have opened this separate issue, to investigate the wrong values being returned by `blockhash` in Solidity contracts.

**Comment by bluesign** [comment]
related code: https://github.com/onflow/flow-go/blob/22daf5cdccbe3dc4af7e239495d54ed4c9d304f0/fvm/evm/handler/blockHashList.go#L78-L100

my investigation so far: 
- Metadata is updating on mainnet, but buckets are not updating at all.

**Comment by zhangchiqing** [comment]
Fixed by https://github.com/onflow/flow-go/pull/6734
