### ISSUE TITLE
[EFM Recovery] Backward-compatibility for `DKGIndexMap` field

### ISSUE THREAD

**Issue by jordanschalm** [onflow/flow-go#6785]
## Context
We are deploying EFM Recovery as a Protocol HCU, so software changes need to be backward compatible with existing state and upgrade-safe. See [Upgrade Plan (Notion)](https://www.notion.so/flowfoundation/EFM-Recovery-Release-Upgrade-Plan-14d1aee1232480228a87e43933815285?pvs=4) for details.

This issue is for implementing backward-compatibility for the `EpochCommit.DKGIndexMap`. In the current software version, the field exists, but it is always nil. The upgraded software version must be able to handle both instances with a nil field, and instances with a non-nil field.

## Definition of Done
- Modify codepaths where we currently assume non-nil `DKGIndexMap` field
  - `IsValidEpochCommit` (service event validation) 
  - `TestBootstrapInvalidEpochCommit` (validation tests)
  - `DKG.Index` method  (used in signature verification)
- Test that above codepaths, when operating on `EpochCommit` instances with nil `DKGIndexMap` fields, behave correcly

**Comment by durkmurder** [comment]
Implemented in https://github.com/onflow/flow-go/pull/6795
