### ISSUE TITLE
Compare execution effort pre/post Crescendo

### ISSUE THREAD

**Issue by j1010001** [onflow/flow-go#6824]

**Comment by fxamacker** [comment]
Closing as done.  Shared on slack:

- mainnet24 execution effort stats from parsing logs after re-executing 400,000 blocks
- mainnet26 execution effort stats from parsing logs after re-executing 400,000 blocks
- mainnet24 flame graph from CPU profiling verification
- mainnet26 flame graph from CPU profiling verification

Also shared on Google drive: 
- Go CPU profiles used to generate flame graph
