### ISSUE TITLE
Continuous delivery mode might not be stopped as expected

### ISSUE THREAD

**Issue by fxamacker** [onflow/flow-go#807]
## 🐞 Bug Report

The `break` appears to be intended to stop continuous delivery mode but the `break` is a no-op due to its location.
https://github.com/onflow/flow-go/blob/2f7d0dfc4a6b9a072f09a07ca0be631194a15d2b/network/stub/network.go#L275-L287

Replacing `break` with `return` is one possible way to resolve this.

**Comment by turbolent** [comment]
Also, shouldn't it be `go wg.Done()`? The wait group will resolve basically right away right now, no?

**Comment by bluesign** [comment]
> Also, shouldn't it be `go wg.Done()`? The wait group will resolve basically right away right now, no?

I think this is to catch timer before dispose.

**Comment by awfm9** [comment]
It should probably be `defer wg.Done()`.
