### ISSUE TITLE
Building on m1 mac

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-go#809]
## 🐞 Bug Report

make install-tools fails on m1 mac.

## What is the severity of this bug?

**Could have:**

## Reproduction steps

Check out code on m1 mac and follow the instruction until `make install-tools`

## Expected behaviour

It should build

## Specifications

- System: Mac os X Big Sur on  M1 Mac Mini
- Go: 1.16.4

## Additional context

```git diff
diff --git a/crypto/relic_build.sh b/crypto/relic_build.sh
index bb70d3123..a0f98d388 100755
--- a/crypto/relic_build.sh
+++ b/crypto/relic_build.sh
@@ -17,7 +17,7 @@ pushd "$DIR/relic/build"
 #
 GENERAL=(-DTIMER=CYCLE -DCHECK=OFF -DVERBS=OFF)
 LIBS=(-DSHLIB=OFF -DSTLIB=ON)
-COMP=(-DCOMP="-O3 -funroll-loops -fomit-frame-pointer -march=native -mtune=native")
+COMP=(-DCOMP="-O3 -funroll-loops -fomit-frame-pointer -mtune=native")
 RAND=(-DRAND=HASHD -DSEED=)```

seems to fix the problem.

**Comment by huitseeker** [comment]
Cross-ref #756.

@tarakby would it be enough to run with `-O3 -mavx512f -mavx512cd` to cover the post Knights Landing / Skylake world for relic? We'd miss e.g. IFMA, but I'm not sure we use it anyway?

**Comment by tarakby** [comment]
@huitseeker  The issue is that this script needs to be as generic as possible, as it is used on different machines for which we can't make AVX support assumptions. I think specifying the AVX flags might make compilation fail on some machines.

**Comment by tatujan** [comment]
#823 fixes make-install but running tests(e.g. make test) fails due to unable to link files built for macOS-x86_64.  Build process should not have build x86_64 files but macOS-arm64. I am not sure if this is related to #1176 or something related to this issue. Confused.

**Comment by tarakby** [comment]
I understand the issue you described is related to running tests on ARM ? I don't think this is related to #1176.
It would be good to open a new issue and provide more details about the error please.
